import {canonicalShow,normalizeMembers} from '../product/identity.js';
import {ingredients} from '../product/engine.js';
import {dietFits} from '../product/diets.js';
import {aiRequest} from './ai.js';
import {meals,mealById,defaults,moods,mealCategories} from '../product/catalog.js';
import {foodPreferences} from '../product/diets.js';
import {curate,scheduleDinner,connectionModes,discoveryCandidates,compromiseFacts,groupAlternatives} from '../product/curation.js';
import {availability} from './catalog.js';
const fail=(s,status=400)=>{throw Object.assign(Error(s),{status});};
const key=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
const valid=s=>typeof s==='string'&&/^[a-f0-9]{64}$/.test(s);
const digest=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const reply=(d,status=200)=>new Response(JSON.stringify(d),{status,headers:{'content-type':'application/json','cache-control':'no-store','referrer-policy':'no-referrer'}});
async function photoUpload(env,jpeg){if(!env.MEDIA)fail('Photo storage is unavailable.',503);if(typeof jpeg!=='string'||jpeg.length>1200000||!jpeg.startsWith('data:image/jpeg;base64,'))fail('Choose a JPEG smaller than 900 KB.');let bytes;try{bytes=Uint8Array.from(atob(jpeg.split(',')[1]),c=>c.charCodeAt(0));}catch{fail('Invalid photo.');}if(bytes[0]!==255||bytes[1]!==216||bytes[2]!==255)fail('Invalid JPEG.');const pk=key();await env.MEDIA.put('photos/'+pk,bytes,{httpMetadata:{contentType:'image/jpeg'}});return pk;}
async function read(req){const t=await req.text();if(t.length>1400000)fail('This upload is too large.',413);try{return JSON.parse(t);}catch{fail('Invalid request.');}}
export function options(o={}){const region=o.region||'US',services=o.services||[],connectionMode=o.connectionMode||'Mood';if(!/^[A-Z]{2}$/.test(region)||!Array.isArray(services)||services.length>12||services.some(n=>!Number.isInteger(n)||n<1)||!connectionModes.includes(connectionMode))fail('Check your pairing and streaming settings.');return {region,services,connectionMode};}
function prefs(p){const v={...defaults,...p};if(!foodPreferences.includes(v.diet)||!moods.includes(v.mood)||![15,30,45,60].includes(v.cookTime)||![30,45,90,120,180,240,360,600].includes(v.watchTime)||!['Any','Movie','TV episode'].includes(v.format)||!Number.isInteger(v.people)||v.people<1||v.people>8||!['Any','Easy'].includes(v.effort)||typeof v.family!=='boolean')fail('Check the evening limits.');return v;}
export async function curated(env,house,b,members=[]){
 const p=prefs(b.prefs||house.prefs),o=options(b.options||house.options);let ranked=curate({mode:b.mode,sourceId:b.sourceId,prefs:p,memory:house.memory,titles:house.titles||[],members,pantry:house.pantry||[],dinnerAdapted:b.dinnerAdapted,connectionMode:o.connectionMode});
 ranked=discoveryCandidates(ranked,house,b);
 if(o.services.length){const titles=[...new Map(ranked.map(p=>[p.show.id,p.show])).values()].slice(0,b.browse?60:24),available=new Map();for(let i=0;i<titles.length;i+=4){await Promise.all(titles.slice(i,i+4).map(async s=>{const a=await availability(env,s,o.region);if(a.subscription.some(x=>o.services.includes(x.id)))available.set(s.id,a);}));}ranked=ranked.filter(p=>available.has(p.show.id)).map(p=>({...p,availability:available.get(p.show.id)}));}
 if(b.browse){const byTitle=new Map();for(const pair of ranked){const list=byTitle.get(pair.show.id)||[];if(list.length<4)list.push(pair);byTitle.set(pair.show.id,list);}const picks=[];for(let i=0;i<4;i++)for(const list of byTitle.values())if(list[i]&&picks.length<120)picks.push(list[i]);return {picks,prefs:p,options:o,message:picks.length?'':'No catalog choices match these settings.'};}
 const picks=members.length?groupAlternatives(ranked,members):[],seenMeals=new Set(),seenShows=new Set();for(const p of members.length?[]:ranked){if(b.mode==='meal'?seenShows.has(p.show.id):b.mode==='watch'?seenMeals.has(p.meal.id):seenShows.has(p.show.id)||seenMeals.has(p.meal.id))continue;picks.push(p);seenMeals.add(p.meal.id);seenShows.add(p.show.id);if(picks.length===3)break;}
 if(members.some(m=>m.diet==='Plant-based'))p.diet='Plant-based';
 if(members.length){p.watchTime=Math.min(p.watchTime,...members.map(m=>m.watchTime));for(const pick of picks)pick.compromises=compromiseFacts(pick,members);}
 return {picks,prefs:p,options:o,message:picks.length?'':o.connectionMode==='On-screen food'?'No documented dish pairing matches these limits. Try Ratatouille with 45 minutes to cook, or choose Mood.':o.services.length?'No verified subscription match in the current title shortlist. Try another service, region or title.':'No shared pairing meets every submitted limit. Review food preferences, ingredient exclusions and viewing time together.'};
}
async function room(db,token){if(!valid(token))fail('Invalid room link.',404);const r=await db.prepare('SELECT * FROM rooms WHERE id=?').bind(await digest(token)).first();if(!r||r.expires<Date.now())fail('This room expired. Ask the host for a new link.',404);const data=JSON.parse(r.data);data.members=normalizeMembers(data.members);data.picks=(data.picks||[]).map(p=>({...p,show:canonicalShow(p.show)}));return {...r,data};}
async function saveRoom(db,r){const d=await db.prepare('UPDATE rooms SET data=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(r.data),r.id,r.revision).run();if(!d.meta.changes)fail('Someone updated the room. Refresh and try again.',409);r.revision++;}
function roomView(r){const d=r.data;return {name:d.name,revision:r.revision,expires:r.expires,phase:d.phase,members:d.members.map(({token,...m})=>m),picks:d.picks||[],explanationSource:d.explanationSource||'catalog',prefs:d.prefs,message:d.message||'',votes:Object.fromEntries((d.picks||[]).map(p=>[p.meal.id+':'+p.show.id,d.members.filter(m=>m.vote===p.meal.id+':'+p.show.id).length]))};}
function memberInput(b){const name=String(b.name||'').trim(),avoid=b.avoid||[];if(!name||name.length>32||!moods.includes(b.mood)||!foodPreferences.includes(b.diet)||![30,45,90,120,180,240,360,600].includes(b.watchTime)||!['Any','Movie','TV episode'].includes(b.format)||!Array.isArray(avoid)||avoid.length>15||avoid.some(s=>typeof s!=='string'||!s.trim()||s.length>50))fail('Check your name, preferences and ingredients to avoid.');if(b.mealPreference&&!['Any',...mealCategories].includes(b.mealPreference))fail('Choose a meal style.');if(b.vetoTitle!==undefined&&(typeof b.vetoTitle!=='string'||b.vetoTitle.length>100))fail('Keep the title veto under 100 characters.');return {mealPreference:b.mealPreference||'Any',vetoTitle:String(b.vetoTitle||'').trim(),name,mood:b.mood,diet:b.diet,watchTime:b.watchTime,format:b.format,avoid:avoid.map(x=>x.trim().toLowerCase()),vote:null};}
export async function publicSocial(req,env){const u=new URL(req.url),a=u.pathname.split('/').filter(Boolean),method=req.method;
 if(a[1]==='collection-editor'){if(!valid(a[2]))fail('Invalid editor link.',404);const r=await env.DB.prepare('SELECT * FROM collections WHERE id=?').bind(await digest(a[2])).first();if(!r)fail('Editor link unavailable.',404);const d=JSON.parse(r.data),b=method==='PUT'?await read(req):null,t=b?.editKey||u.searchParams.get('editKey');if(!valid(t)||t!==d.editKey)fail('Invalid editor permission.',403);if(method==='PUT'){const previous=d.photo;d.photo=await photoUpload(env,b.jpeg);const saved=await env.DB.prepare('UPDATE collections SET data=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(d),r.id,r.revision).run();if(!saved.meta.changes)fail('The collection changed. Refresh and retry.',409);if(previous)await env.MEDIA.delete('photos/'+previous);}else if(method!=='GET')fail('Method not allowed.',405);return reply({name:d.name,photo:d.photo});}
 if(a[1]==='room'){
 const r=await room(env.DB,a[2]);if(method==='GET')return reply(roomView(r));
 const b=await read(req);if(method!=='POST')fail('Method not allowed.',405);
 if(a[3]==='join'){if(r.data.phase!=='gathering')fail('The host has started voting. Ask them to reopen preferences.');const input=memberInput(b),t=b.memberKey;if(t!==undefined&&!valid(t))fail('Invalid guest key.');const h=t?await digest(t):null,existing=r.data.members.find(m=>m.token===h);if(existing)Object.assign(existing,input);else{if(r.data.members.length>=8)fail('This room already has eight people.');const fresh=key();r.data.members.push({...input,id:crypto.randomUUID(),token:await digest(fresh)});await saveRoom(env.DB,r);return reply({memberKey:fresh,room:roomView(r)});}await saveRoom(env.DB,r);return reply({memberKey:t,room:roomView(r)});}
 if(a[3]==='veto'){
  if(r.data.phase!=='voting')fail('Vetoes are available while voting.');if(!valid(b.memberKey))fail('Join first.',403);
  const h=await digest(b.memberKey),guest=r.data.members.find(m=>m.token===h);if(!guest)fail('Join first.',403);
  if(!r.data.picks.some(p=>p.meal.id+':'+p.show.id===b.choice))fail('Choose a current pairing.');
  if((guest.vetoes||[]).length>=20)fail('You have used 20 vetoes in this room. Start a new room to begin again.');
  guest.vetoes=[...new Set([...(guest.vetoes||[]),b.choice])];r.data.picks=r.data.picks.filter(p=>p.meal.id+':'+p.show.id!==b.choice);r.data.members.forEach(m=>{if(m.vote===b.choice)m.vote=null;});
  r.data.message='A pairing was vetoed and removed for everyone. Vote on the remaining choices or find three new pairings.';if(!r.data.picks.length)r.data.phase='gathering';
  await saveRoom(env.DB,r);return reply(roomView(r));
 }
 if(a[3]==='vote'){if(r.data.phase!=='voting')fail('Voting is not open.');if(!valid(b.memberKey))fail('Join the room first.',403);const h=await digest(b.memberKey),guest=r.data.members.find(m=>m.token===h);if(!guest)fail('Join the room first.',403);if(!r.data.picks.some(p=>p.meal.id+':'+p.show.id===b.choice))fail('Choose a current pairing.');guest.vote=b.choice;await saveRoom(env.DB,r);return reply(roomView(r));}fail('Not found.',404);
 }
 if(a[1]==='collection-share'&&method==='GET'){if(!valid(a[2]))fail('Invalid collection link.',404);const r=await env.DB.prepare('SELECT data FROM collections WHERE id=?').bind(await digest(a[2])).first();if(!r)fail('This collection is no longer shared.',404);const d=JSON.parse(r.data);if(!d.shared)fail('This collection is no longer shared.',404);return reply({name:d.name,notes:d.notes,photo:d.photo,meal:mealById(d.mealId),show:d.show,prefs:d.prefs});}
 if(a[1]==='photo'&&method==='GET'){if(!valid(a[2])||!env.MEDIA)fail('Photo unavailable.',404);const obj=await env.MEDIA.get('photos/'+a[2]);if(!obj)fail('Photo unavailable.',404);return new Response(obj.body,{headers:{'content-type':'image/jpeg','cache-control':'private,max-age=3600','x-content-type-options':'nosniff','referrer-policy':'no-referrer'}});}
 return null;
}
export async function social(req,env,ctx){const u=new URL(req.url),a=u.pathname.split('/').filter(Boolean),method=req.method,{id,row,save}=ctx,house=row.data;
 if(a[1]==='browse'&&method==='POST')return reply(await curated(env,house,{...(await read(req)),browse:true}));
 if(a[1]==='curate'&&method==='POST')return reply(await curated(env,house,await read(req)));
 if(a[1]==='options'&&method==='PUT'){house.options=options(await read(req));await save();return reply(house.options);}
 if(a[1]==='rooms'){
 if(method==='GET'&&!a[2]){const rs=await env.DB.prepare('SELECT data,expires FROM rooms WHERE household=? AND expires>?').bind(id,Date.now()).all();return reply({rooms:rs.results.map(r=>({key:JSON.parse(r.data).key,name:JSON.parse(r.data).name,expires:r.expires}))});}
 if(method==='POST'&&!a[2]){const b=await read(req),count=await env.DB.prepare('SELECT COUNT(*) AS n FROM rooms WHERE household=? AND expires>?').bind(id,Date.now()).first();if(count.n>=10)fail('You already have ten active rooms.');const k=key(),name=String(b.name||'Our evening').trim().slice(0,60),data={key:k,name,phase:'gathering',members:[],picks:[],prefs:prefs(b.prefs||house.prefs),options:options(b.options||house.options)};await env.DB.prepare('INSERT INTO rooms(id,household,data,expires) VALUES(?,?,?,?)').bind(await digest(k),id,JSON.stringify(data),Date.now()+86400000).run();return reply({key:k,room:roomView({data,revision:0,expires:Date.now()+86400000})},201);}
 const r=await room(env.DB,a[2]);if(r.household!==id)fail('Only the host can change this room.',403);
 if(method==='POST'&&a[3]==='match'){if(!r.data.members.length)fail('Have at least one person join first.');r.data.hostPrefs ||= {...r.data.prefs};const result=await curated(env,house,{prefs:{...r.data.hostPrefs,people:r.data.members.length},options:r.data.options},r.data.members);r.data.explanationSource='catalog';
 try{if(result.picks.length){const explained=await aiRequest(new Request(req,{body:JSON.stringify({mode:'group',prompt:'Explain the shared choices and proposed compromises.',group:result.picks.map(p=>({id:p.meal.id+':'+p.show.id,meal:p.meal.name,show:p.show.name,strategy:p.strategy,evidence:p.strategyDetail,members:p.compromises}))})}),{...env,AI_TIMEOUT_MS:25000},house,id,row.revision);for(const p of result.picks){const x=explained.picks.find(x=>x.id===p.meal.id+':'+p.show.id);if(x?.reason){p.reason=x.reason;p.aiExplained=true;}}r.data.explanationSource=result.picks.some(p=>p.aiExplained)?'ai':'catalog';}}catch{ /* The checked group choices remain available if AI is unavailable. */ }
 r.data.picks=result.picks;r.data.message=result.message;r.data.prefs=result.prefs;r.data.phase=result.picks.length?'voting':'gathering';r.data.members.forEach(m=>m.vote=null);await saveRoom(env.DB,r);return reply(roomView(r));}
 if(method==='POST'&&a[3]==='reveal'){if(r.data.phase!=='voting')fail('Find pairings before revealing.');if(r.data.members.some(m=>!m.vote))fail('Wait until everyone has voted.');r.data.phase='revealed';r.data.picks.sort((x,y)=>r.data.members.filter(m=>m.vote===y.meal.id+':'+y.show.id).length-r.data.members.filter(m=>m.vote===x.meal.id+':'+x.show.id).length);await saveRoom(env.DB,r);return reply(roomView(r));}
 if(method==='POST'&&a[3]==='reopen'){r.data.phase='gathering';r.data.picks=[];r.data.members.forEach(m=>m.vote=null);await saveRoom(env.DB,r);return reply(roomView(r));}fail('Not found.',404);
 }
 if(a[1]==='schedule'&&method==='POST'){const b=await read(req),n=house.nights.find(n=>n.id===b.nightId);if(!n)fail('Night not found.',404);if(n.status!=='planned'||n.watchStarted)fail('Set a dinner time before cooking or viewing starts.');try{Object.assign(n,scheduleDinner(n,mealById(n.mealId),b.dinnerAt,b.dinnerMinutes));}catch(e){fail(e.message);}await save();return reply(n);}
 if(a[1]==='collections'){
 if(method==='GET'&&!a[2]){const r=await env.DB.prepare('SELECT data FROM collections WHERE household=?').bind(id).all();return reply({collections:r.results.map(x=>JSON.parse(x.data))});}
 if(method==='POST'&&!a[2]){const b=await read(req),n=house.nights.find(n=>n.id===b.nightId);if(!n)fail('Save an evening before adding it to a collection.',404);const count=await env.DB.prepare('SELECT COUNT(*) AS n FROM collections WHERE household=?').bind(id).first();if(count.n>=60)fail('Your collection has 60 entries. Remove an older one first.');const k=key(),d={key:k,name:String(b.name||mealById(n.mealId).name).slice(0,80),notes:String(b.notes||'').slice(0,1500),mealId:n.mealId,show:n.show,prefs:n.prefs,shared:false,photo:null,editKey:key()};await env.DB.prepare('INSERT INTO collections(id,household,data) VALUES(?,?,?)').bind(await digest(k),id,JSON.stringify(d)).run();return reply(d,201);}
 if(!valid(a[2]))fail('Collection not found.',404);const r=await env.DB.prepare('SELECT * FROM collections WHERE id=? AND household=?').bind(await digest(a[2]),id).first();if(!r)fail('Collection not found.',404);const d=JSON.parse(r.data);
 if(method==='DELETE'){await env.DB.prepare('DELETE FROM collections WHERE id=? AND household=?').bind(r.id,id).run();if(d.photo&&env.MEDIA)await env.MEDIA.delete('photos/'+d.photo);return reply({deleted:true});}
 if(method==='PUT'){const b=await read(req);if(a[3]==='photo'){d.photo=await photoUpload(env,b.jpeg);}else{if(typeof b.name!=='string'||!b.name.trim()||b.name.length>80||typeof b.notes!=='string'||b.notes.length>1500||typeof b.shared!=='boolean')fail('Check the collection name and notes.');Object.assign(d,{name:b.name.trim(),notes:b.notes,shared:b.shared});}
 const saved=await env.DB.prepare('UPDATE collections SET data=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(d),r.id,r.revision).run();if(!saved.meta.changes)fail('This collection changed. Refresh and try again.',409);return reply(d);}
 }return null;
}

export async function approveGroup(env,household,roomKey,meal,show,prefs,adapted){
 const r=await room(env.DB,roomKey);if(r.household!==household)fail('Only the host can save this group evening.',403);
 if(r.data.phase!=='revealed'||!r.data.picks.some(p=>p.meal.id===meal.id&&p.show.id===show.id))fail('Reveal the group result before approving it.');
 if(prefs.people!==r.data.members.length)fail('Keep the approved group size or start a new group plan.');
 const actual=ingredients(meal,prefs.people,adapted);
 if(r.data.members.some(m=>!dietFits(meal,m.diet)||(m.diet==='Plant-based'&&!adapted)||show.minutes>m.watchTime||(m.format!=='Any'&&show.kind!==m.format)||(m.vetoes||[]).includes(meal.id+':'+show.id)||(m.vetoTitle&&show.name.toLowerCase().includes(m.vetoTitle.toLowerCase()))||actual.some(i=>(m.avoid||[]).some(x=>i.name.toLowerCase().includes(x)))))fail('The adapted meal no longer respects everyone’s submitted limits. Undo the adaptation or reopen group preferences.');
 return {memberCount:r.data.members.length,members:r.data.members.map(({token,vote,...m})=>m),compromises:compromiseFacts({meal,show},r.data.members)};
}
