import test from 'node:test';
import assert from 'node:assert/strict';
import {shortlistPairs,reviewConnections} from '../server/matching-review.js';
import {eligiblePairs,validatePicks,aiRequest} from '../server/ai.js';
import {defaults,mealById} from '../product/catalog.js';
import {foodReferences} from '../server/food-references.js';
import {openDb} from '../server/local-db.js';
const prefs={...defaults,cookTime:45,watchTime:180};
const fixed=()=>eligiblePairs({memory:{}},prefs,{showId:'avengers'});
test('shortlist preserves familiar choices, exact title and hard ingredient exclusions',()=>{const all=eligiblePairs({memory:{dislikedIngredients:['turkey']}},prefs,{showId:'avengers'}),short=shortlistPairs(all);assert.ok(short.length<=80);assert.ok(short.every(p=>p.show.id==='avengers'&&!p.meal.ingredients.some(i=>/turkey/i.test(i[0]))));assert.ok(all.filter(p=>p.meal.familiar).every(p=>short.some(x=>x.id===p.id)));});
test('an invented ingredient cannot earn a reviewed connection',async()=>{const p=fixed()[0];const d=await reviewConnections({picks:[{id:p.id,pairingType:'setting'}]},[p],{AI_GENERATE:async()=>({reviews:[{id:p.id,verdict:'keep',mealEvidence:['Marmalade'],tableEcho:'An invented recipe connection.',storyCue:'Some story cue',evidenceQuote:p.show.description}]})},prefs,false);assert.equal(d.picks[0].pairingType,'practical');});
test('model verdict and exact quote are both required for production setting labels',()=>{const p=fixed()[0],pick={id:p.id,pairingType:'setting',evidenceQuote:p.show.description.slice(0,100),tableEcho:'A supposedly concrete dinner link.'};assert.equal(validatePicks({picks:[pick]},[p],{requireReview:true})[0].pairingType,'practical');assert.equal(validatePicks({picks:[{...pick,connectionReviewed:true,evidenceQuote:'This is an invented London restaurant.'}]},[p],{requireReview:true})[0].pairingType,'practical');});
test('food references are bound to the correct film and a relevant recipe format',()=>{const pairs=fixed(),p=pairs.find(x=>x.meal.id==='turkey-pita-pockets'),r=foodReferences(p.show)[0],pick={id:p.id,pairingType:'setting',connectionReviewed:true,evidenceQuote:r.text,sourceId:r.id,tableEcho:'A filled pita inspired by the shawarma reference, not the film recipe.'};assert.equal(validatePicks({picks:[pick]},[p],{requireReview:true})[0].pairingType,'setting');const taco=pairs.find(x=>x.meal.id==='chicken-pepper-tacos');assert.equal(validatePicks({picks:[{...pick,id:taco.id}]},[taco],{requireReview:true})[0].pairingType,'practical');const other={...p,id:p.meal.id+'|different',show:{...p.show,id:'different',provider:null}};assert.equal(validatePicks({picks:[{...pick,id:other.id}]},[other],{requireReview:true})[0].pairingType,'practical');});
test('a rejected story connection cannot survive in the overall summary',async()=>{const DB=openDb();try{const r=await aiRequest(new Request('https://test/api/ai',{method:'POST',body:JSON.stringify({mode:'plan',primary:true,prompt:'Find dinner.',showId:'avengers',prefs})}),{DB,AI_GENERATE:async(_,input)=>input.allowedPairs?{answer:'These are all authentic movie dishes!',picks:[{id:input.allowedPairs[0],pairingType:'setting',storyCue:'Invented scene',tableEcho:'A made-up connection to a feast.'}]}:{reviews:[]}}, {prefs,memory:{},nights:[],pantry:[]},'review-test',0);assert.equal(r.picks[0].pairingType,'practical');assert.match(r.answer,/no strong food connection/);assert.ok(!r.answer.includes('authentic'));}finally{DB.close();}});

import {diverseFinalists} from '../server/pairing-quality.js';
test('different formats with nearly identical fillings lose to a distinct ingredient alternative',()=>{const make=(id,category,names)=>({id,meal:{id,category,familiar:true,ingredients:names.map(n=>[n])},show:{id:'same'},pairingType:'practical'});const a=make('a','Wraps',['Black beans','Corn','Tortilla']),b=make('b','Burgers',['Black beans','Corn','Bun']),c=make('c','Pasta',['Pasta','Tomato','Cheese']),d=make('d','Soup',['Mushrooms','Barley','Onion']);assert.deepEqual(diverseFinalists([a,b,c,d],[a,b,c,d]).map(p=>p.id),['a','c','d']);});
test('reviewed atmosphere metaphors still fail the final editorial check',async()=>{const p=fixed()[0];const r=await reviewConnections({picks:[{id:p.id,pairingType:'setting'}]},[p],{AI_GENERATE:async()=>({reviews:[{id:p.id,verdict:'keep',mealEvidence:[p.meal.ingredients[0][0]],storyCue:'A specific story fact',tableEcho:'This dinner evokes European street food and atmosphere.',evidenceQuote:p.show.description.slice(0,100)}]})},prefs,false);assert.equal(r.picks[0].pairingType,'practical');});
