import test from 'node:test';
import assert from 'node:assert/strict';
import {openDb} from '../server/local-db.js';
import {api} from '../server/worker.js';
import {meals,defaults} from '../product/catalog.js';
import {kidsSteps} from '../product/kids-cooking.js';
import {recipeSteps} from '../product/engine.js';
async function setup(){const DB=openDb(),env={DB};const h=await (await api(new Request('https://test/api/household',{method:'POST'}),env)).json();const call=(route,method='GET',body)=>api(new Request('https://test/api/'+route,{method,headers:{'content-type':'application/json','x-household-key':h.key},...(body?{body:JSON.stringify(body)}:{})}),env);return {DB,call};}
test('parent lock survives reload and rejects search, takeout, AI and preference bypasses',async()=>{const {DB,call}=await setup();try{const state=await (await call('parental')).json();assert.ok(state.titles.length);const approved=[state.titles[0].id];assert.equal((await call('parental','POST',{action:'enable',pin:'123456',approvedShowIds:approved})).status,200);const h=await (await call('household')).json();assert.equal(h.kidsMode,true);assert.deepEqual(h.kidsTitles.map(t=>t.id),approved);assert.deepEqual(h.nights,[]);assert.ok(!JSON.stringify(h).includes('pin_hash'));for(const [route,method,body] of [['catalog/search?q=crime','GET'],['companion','POST',{kind:'order'}],['ai','POST',{mode:'plan'}],['preferences','PUT',{prefs:{...defaults,family:false}}],['nights','POST',{}],['browse','POST',{}]])assert.equal((await call(route,method,body)).status,403,route);assert.equal((await call('kids','POST',{action:'choices',showId:'not-approved'})).status,403);assert.equal((await call('parental','POST',{action:'disable',pin:'999999'})).status,403);assert.equal((await call('parental','POST',{action:'disable',pin:'123456'})).status,200);assert.ok(!(await (await call('household')).json()).kidsMode);}finally{DB.close();}});
test('cooking needs a parent PIN and preserves ingredients and original steps',async()=>{const {DB,call}=await setup();try{const state=await (await call('parental')).json(),showId=state.titles[0].id;await call('parental','POST',{action:'enable',pin:'123456',approvedShowIds:[showId]});const choices=await (await call('kids','POST',{action:'choices',showId})).json();assert.ok(choices.meals.length);const mealId=choices.meals[0].id;assert.equal((await call('kids','POST',{action:'recipe',showId,mealId})).status,403);const recipe=await (await call('kids','POST',{action:'recipe',showId,mealId,pin:'123456'})).json();assert.ok(recipe.ingredients.length);assert.ok(recipe.steps.every(s=>s.adultRequired&&s.adultInstruction===s.instruction));const row=await DB.prepare('SELECT pin_hash,salt FROM parent_controls').first();assert.notEqual(row.pin_hash,'123456');assert.ok(row.salt);}finally{DB.close();}});
test('five wrong PIN attempts trigger a timed lockout',async()=>{const {DB,call}=await setup();try{const state=await (await call('parental')).json();await call('parental','POST',{action:'enable',pin:'123456',approvedShowIds:[state.titles[0].id]});for(let i=0;i<5;i++)assert.equal((await call('parental','POST',{action:'disable',pin:'000000'})).status,403);assert.equal((await call('parental','POST',{action:'disable',pin:'123456'})).status,429);}finally{DB.close();}});
test('every kids recipe retains its adult instructions and timer',()=>{for(const m of meals){const base=recipeSteps(m,false,'Confident'),kids=kidsSteps(base);assert.equal(kids.length,base.length);kids.forEach((s,i)=>{assert.equal(s.adultInstruction,base[i].instruction);assert.equal(s.seconds,base[i].seconds);assert.equal(s.adultRequired,true);});}});

test('kids session restores step and timer, rejects invalid progress, and expires approval',async()=>{const {DB,call}=await setup();try{const {titles}=await (await call('parental')).json(),showId=titles[0].id;await call('parental','POST',{action:'enable',pin:'123456',approvedShowIds:[showId],helperLevel:'Growing cook'});const {meals}=await (await call('kids','POST',{action:'choices',showId})).json();const r=await (await call('kids','POST',{action:'recipe',showId,mealId:meals[0].id,pin:'123456'})).json();const sessionId=r.session.id;assert.equal((await call('kids','POST',{action:'progress',sessionId,step:999,done:false})).status,400);assert.equal((await call('kids','POST',{action:'progress',sessionId,step:1,done:false,timer:'start'})).status,200);const saved=await (await call('kids')).json();assert.equal(saved.session.step,1);assert.ok(saved.session.timer>=Date.now());assert.deepEqual(saved.session.recipe,r.session.recipe);assert.equal((await call('kids','POST',{action:'progress',sessionId:'wrong',step:1,done:false})).status,409);saved.session.expires=Date.now()-1;await DB.prepare('UPDATE parent_controls SET session=?').bind(JSON.stringify(saved.session)).run();assert.equal((await (await call('kids')).json()).session,null);assert.equal((await call('kids','POST',{action:'progress',sessionId,step:1,done:false})).status,409);}finally{DB.close();}});
test('PIN changes and one-use recovery protect the parent area without exposing secrets',async()=>{const {DB,call}=await setup();try{const {titles}=await (await call('parental')).json();const enabled=await (await call('parental','POST',{action:'enable',pin:'123456',approvedShowIds:[titles[0].id]})).json();assert.ok(enabled.recoveryCode);const row=await DB.prepare('SELECT recovery_hash FROM parent_controls').first();assert.notEqual(row.recovery_hash,enabled.recoveryCode);assert.ok(!JSON.stringify(await (await call('parental')).json()).includes(enabled.recoveryCode));assert.equal((await call('parental','POST',{action:'change-pin',pin:'123456',newPin:'654321'})).status,200);assert.equal((await call('parental','POST',{action:'disable',pin:'123456'})).status,403);assert.equal((await call('parental','POST',{action:'recover',recoveryCode:'wrong',newPin:'333333'})).status,403);assert.equal((await call('parental','POST',{action:'recover',recoveryCode:enabled.recoveryCode,newPin:'333333'})).status,200);assert.equal((await call('parental','POST',{action:'recover',recoveryCode:enabled.recoveryCode,newPin:'444444'})).status,403);assert.equal((await call('parental','POST',{action:'recovery-code',pin:'333333'})).status,200);assert.ok(!(await (await call('household')).json()).kidsMode);}finally{DB.close();}});
test('helper levels tailor approved tasks while preserving every adult direction',()=>{const meal=meals.find(m=>m.id==='tomato-pasta'),base=recipeSteps(meal,false,'Confident'),little=kidsSteps(base,meal,'Little helper'),growing=kidsSteps(base,meal,'Growing cook');assert.notEqual(little[1].helperInstruction,growing[1].helperInstruction);assert.match(growing[1].helperInstruction,/basil/);for(const m of meals){const original=recipeSteps(m,false,'Confident');kidsSteps(original,m,'Growing cook').forEach((s,i)=>{assert.equal(s.adultInstruction,original[i].instruction);assert.equal(s.seconds,original[i].seconds);assert.equal(s.adultRequired,true);});}});
