import {MatchingStage} from './MatchingStage';
import {PairingReason} from './PairingReason';
import {MealSignals} from './MealSignals';
import {PairingHero} from './PairingHero';
import {RecipeArt} from './RecipeArt';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Animated,Image,Linking,Platform,ScrollView,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import {TVButton as Button} from './TVButton';
import {api} from './api';
import {curate,connection} from './catalog/curation';
import {mealById,shows} from './catalog/catalog';
import {recipeSteps} from './catalog/engine';
import {ConnectionBadge,DecisionReceipt} from './PairingIntelligence';
const availabilityCache=new Map<string,Promise<any>>();
export function AvailabilityBadge({show,region='US'}:any){const [data,setData]=useState<any>(null),[failed,setFailed]=useState(false);const provider=show.provider||(()=>{const m=show.source?.match(/themoviedb.org\/(movie|tv)\/(\d+)/);return m?{type:m[1],id:m[2]}:null;})();useEffect(()=>{let alive=true;setData(null);setFailed(false);if(!provider)return;const key=provider.type+provider.id+region;if(!availabilityCache.has(key))availabilityCache.set(key,api(`catalog/availability?type=${provider.type}&id=${provider.id}&region=${region}`).catch(e=>{availabilityCache.delete(key);throw e;}));availabilityCache.get(key)!.then(x=>{if(alive)setData(x);}).catch(()=>{if(alive)setFailed(true);});return()=>{alive=false;};},[show.id,region]);const sub=data?.subscription?.map((x:any)=>x.name).join(', '),rent=data?.rent?.map((x:any)=>x.name).join(', '),buy=data?.buy?.map((x:any)=>x.name).join(', ');return <View style={b.availability}><Text style={b.availabilityText}>{!provider||failed?'Availability unknown':!data?'Checking where to watch…':sub?'Subscription · '+sub:rent?'Rent · '+rent:buy?'Buy · '+buy:'No regional listing found'} · {region}</Text>{data&&<Text style={b.small}>JustWatch via TMDB{show.kind==='TV episode'?' · Series listing; check episode':''}</Text>}</View>;}
const scrollPositions:Record<string,{x:number,y:number}>={};
export function BrowseScroll({memoryKey,children,horizontal=false,style,contentContainerStyle}:any){const ref=useRef<ScrollView>(null);return <ScrollView testID={horizontal?undefined:"main-scroll"} ref={ref} horizontal={horizontal} style={style} contentContainerStyle={contentContainerStyle} showsHorizontalScrollIndicator={false} scrollEventThrottle={100} onScroll={e=>{scrollPositions[memoryKey]=e.nativeEvent.contentOffset;}} onContentSizeChange={()=>{const p=scrollPositions[memoryKey];if(p)ref.current?.scrollTo({...p,animated:false});}}>{children}</ScrollView>;}
function Rail({title,subtitle,children,id}:any){const {width}=useWindowDimensions();return <View testID={'remote-row-'+id} style={[b.rail,{paddingLeft:width<900?20:52}]}><Text style={b.h2}>{title}</Text>{!!subtitle&&<Text style={[b.small,{marginBottom:12}]}>{subtitle}</Text>}<BrowseScroll horizontal memoryKey={'rail-'+id} contentContainerStyle={{padding:12,paddingRight:52,gap:24}}>{children}</BrowseScroll></View>;}
export function EveningCard({pair,watchArt,mealArt,onChoose,onDetails,focusKey,label,titleOnly=false}:any){
 const {width}=useWindowDimensions(),cardWidth=width<900?Math.min(320,width-56):width>=1600?420:360,matched=!titleOnly;
 return <View style={{width:cardWidth,gap:8}}><Button card focusKey={focusKey} style={{width:cardWidth}} onPress={()=>onChoose(pair)}><View style={{height:cardWidth*9/16}}><Image accessibilityLabel={pair.show.name+' artwork'} source={watchArt(pair.show,true)} style={StyleSheet.absoluteFill}/><LinearGradient colors={['transparent','#090F1CCC']} style={StyleSheet.absoluteFill}/>{matched&&<RecipeArt meal={pair.meal} style={[b.smallDish,{width:100,height:80}]}/>}<Text style={[b.cardBadge,{fontSize:17}]}>{label||(matched?'DINNER + A SHOW':pair.show.kind)}</Text></View><View style={{padding:18,backgroundColor:'#111927',minHeight:matched?160:128}}><Text numberOfLines={2} style={{color:'#FFF',fontSize:28,lineHeight:35,fontWeight:'800',minHeight:70}}>{pair.show.name}</Text>{matched?<Text numberOfLines={1} style={{color:'#FFD1B6',fontSize:23,lineHeight:32}}>{pair.meal.name}</Text>:null}<Text style={{color:'#C7D4E7',fontSize:22,lineHeight:31,marginTop:6}}>{matched?pair.meal.minutes+'m cook · ':''}{pair.show.minutes}m watch</Text></View></Button>{matched&&onDetails&&<Button quiet focusKey={focusKey&&focusKey+'-details'} onPress={()=>onDetails(pair)}>Pairing details</Button>}</View>;
}
export function Discover({house,prefs,options,featured,watchArt,mealArt,onChoose,onDetails,onAdjust,onSearch,onAI,onOpenNight,onGroup,onKitchen,onPantry,onSurprise,onReplay,onNewStory}:any){
 const {width}=useWindowDimensions(),wide=width>=900;
 const [ai,setAI]=useState<any>(null),[aiLoading,setAILoading]=useState(true),[retry,setRetry]=useState(0),[catalogResult,setCatalog]=useState<any>({key:'',picks:[]}),[catalogError,setCatalogError]=useState(''),[catalogLoading,setCatalogLoading]=useState(false),[collection,setCollection]=useState('For you'),[position,setPosition]=useState(0);
 const spotlightSet=useRef<{key:string,items:any[]}|null>(null);
 const requestKey=JSON.stringify({prefs,memory:house.memory,pantry:house.pantry,options,retry});
 const catalog=catalogResult.key===requestKey?catalogResult.picks:[];
 useEffect(()=>{let active=true;spotlightSet.current=null;setAI(null);setAILoading(true);setPosition(0);api('recommendations','POST',{prefs,options,refresh:retry>0}).then(r=>{if(active)setAI({...r,requestKey});}).catch(()=>{if(active)setAI({answer:'Your AI pairings could not load. Browse a title or try again.',picks:[]});}).finally(()=>{if(active)setAILoading(false);});return()=>{active=false;};},[requestKey]);
 useEffect(()=>{let active=true;setCatalogError('');setCatalogLoading(true);api('browse','POST',{prefs,options}).then(r=>{if(active)setCatalog({key:requestKey,picks:r.picks||[]});}).catch(()=>{if(active)setCatalogError('The catalog could not load. Try again in a moment.');}).finally(()=>{if(active)setCatalogLoading(false);});return()=>{active=false;};},[requestKey]);
 const unique=(items:any[])=>{const ids=new Set();return items.filter(p=>{if(!p.show||ids.has(p.show.id))return false;ids.add(p.show.id);return true;}).slice(0,10);};
 const choices=(ai?.requestKey===requestKey&&ai?.recommendationSource==='ai'?ai.picks||[]:[]).map((p:any)=>({...p,decisionReceipt:ai?.decisionReceipt}));
 if(spotlightSet.current?.key!==requestKey)spotlightSet.current=null;
 if(!spotlightSet.current&&!aiLoading&&(choices.length||catalog.length))spotlightSet.current={key:requestKey,items:choices.length?choices:unique(catalog).slice(0,3)};
 const spotlights=spotlightSet.current?.items||[],spotlight=spotlights[position%Math.max(1,spotlights.length)];
 const resume=house.nights.filter((n:any)=>n.status!=='complete'),favorites=house.nights.filter((n:any)=>n.feedback?.meal==='again'&&n.feedback?.pairing!=='miss');
 const collections=[{name:'For you',caption:'Your kind of evening',color:'#264B78',mood:''},{name:'Family Favorites',caption:'Everyone at the table',color:'#176263',mood:'Lighthearted'},{name:'Date Night',caption:'Dinner for two',color:'#71375D',mood:'Romantic'},{name:'Adventure Night',caption:'Make a night of it',color:'#73472B',mood:'Adventure'},{name:'Comfort Food',caption:'Stay in. Settle in.',color:'#454178',mood:'Cozy'}];
 const collectionPairs=unique(catalog.filter((p:any)=>collection==='For you'?true:collection==='Family Favorites'?p.show.family:p.show.mood===collections.find(c=>c.name===collection)?.mood));
 const displayed=new Set(spotlight?[spotlight.show.id]:[]);
 const distinctRow=(items:any[])=>unique(items).filter(p=>{if(displayed.has(p.show.id))return false;displayed.add(p.show.id);return true;});
 const row=(id:string,title:string,items:any[],personal=false)=>{const remaining=distinctRow(items);return remaining.length?<Rail id={id} title={title}>{remaining.map(p=><EveningCard key={p.show.id+p.meal.id} pair={p} watchArt={watchArt} mealArt={mealArt} titleOnly={!personal} onChoose={personal?onChoose:(choice:any)=>onAdjust(choice.show)} onDetails={personal?onDetails:undefined} focusKey={id+p.show.id+p.meal.id}/>)}</Rail>:null;};
 return <BrowseScroll memoryKey="discover" contentContainerStyle={{paddingBottom:50,backgroundColor:'#070B14'}}>
 {!!resume.length&&<View testID="remote-row-resume" style={[b.footer,{margin:wide?32:20,padding:24}]}><Text style={b.kicker}>PICK UP WHERE YOU LEFT OFF</Text><Text style={b.h3}>{resume[0].show?.name||shows.find((s:any)=>s.id===resume[0].showId)?.name||'Your saved evening'}</Text><Text style={b.small}>With {mealById(resume[0].mealId).name}</Text><Button primary focusKey={'resume'+resume[0].id} onPress={()=>onOpenNight(resume[0])}>{resume[0].watchStarted?'Open tonight’s plan':resume[0].status==='cooking'?'Continue cooking →':'Continue my evening →'}</Button></View>}
 {spotlight?<PairingHero pair={spotlight} source={spotlight.aiExplained===true?'ai':'catalog'} pending={aiLoading} watchArt={watchArt} onChoose={spotlight.aiExplained===true?onChoose:(p:any)=>onAdjust(p.show)} onDetails={onDetails} onSearch={()=>onSearch('watch')} position={position%spotlights.length} count={spotlights.length} onPosition={setPosition}/>:<View style={[b.empty,{minHeight:360,justifyContent:'center'}]}>{aiLoading?<MatchingStage compact/>:<Text style={b.kicker}>TONIGHT STARTS HERE</Text>}{!aiLoading&&<Text style={[b.h2,{fontSize:wide?54:38,lineHeight:wide?62:46}]}>What are we watching?</Text>}<Text style={b.meta}>Choose your title. We’ll find its dinner.</Text><View style={b.actions}><Button primary onPress={()=>onSearch('watch')}>Search movies & shows</Button><Button onPress={onSurprise}>Surprise me</Button></View><Text style={b.small}>{aiLoading||catalogLoading?'Loading your evening picks…':ai?.answer||catalogError||'No titles fit your current limits.'}</Text>{!aiLoading&&!catalogLoading&&<Button onPress={()=>setRetry(v=>v+1)}>Try again</Button>}</View>}
 <View style={[b.household,{paddingHorizontal:wide?52:20,paddingBottom:24}]}><Text style={[b.small,{flex:1}]}>{prefs.people} people · {prefs.cookTime}m cooking · {prefs.diet}{options.services.length?' · '+options.services.length+' selected services':''}</Text><Button quiet onPress={()=>onSearch('watch')}>Pick a different title</Button><Button quiet onPress={onKitchen}>Adjust</Button></View>
 <View testID="remote-row-moods" style={{marginBottom:36,paddingLeft:wide?52:20}}><BrowseScroll horizontal memoryKey="mood-hubs" contentContainerStyle={{padding:10,paddingRight:40,gap:18}}>{collections.map(c=>{const art=catalog.find((p:any)=>c.mood?p.show.mood===c.mood:true)?.show;return <Button key={c.name} card selected={collection===c.name} focusKey={'hub'+c.name} onPress={()=>setCollection(c.name)} style={{width:wide?240:220}}><View style={{height:132,backgroundColor:c.color,justifyContent:'flex-end',padding:20}}>{art&&<Image accessible={false} source={watchArt(art,true)} style={[StyleSheet.absoluteFill,{opacity:.25}]}/>}<Text style={{color:'#fff',fontSize:27,lineHeight:34,fontWeight:'900'}}>{c.name}</Text><Text style={{color:'#F0F2FA',fontSize:18,lineHeight:25,marginTop:6}}>{c.caption}</Text></View></Button>;})}</BrowseScroll></View>
 {collection==='For you'?<>{row('ai','Picked for your table',choices,true)}{!aiLoading&&!choices.length&&<View style={{paddingHorizontal:wide?52:20,marginBottom:30}}><Text style={b.small}>{ai?.answer||'AI picks are unavailable right now.'}</Text><Button quiet onPress={()=>setRetry(v=>v+1)}>Retry AI dinner picks</Button></View>}{row('quick','One episode tonight',catalog.filter((p:any)=>p.show.kind==='TV episode'&&p.show.minutes<=60))}{row('movies','Make it a movie night',catalog.filter((p:any)=>p.show.kind==='Movie'))}{row('explore','Explore something different',catalog)}</>:collectionPairs.length?row(collection,collection,collectionPairs):<View style={b.empty}><Text style={b.meta}>{catalogLoading?'Loading titles…':'No '+collection.toLowerCase()+' titles fit your limits.'}</Text><Button onPress={onKitchen}>Adjust preferences</Button><Button onPress={()=>setCollection('For you')}>Back to For you</Button></View>}
 {!!favorites.length&&<Rail id="replay" title="Worth another evening">{favorites.slice(0,6).map((n:any)=>{const show=n.show||shows.find((x:any)=>x.id===n.showId);return show?<EveningCard key={n.id} pair={{meal:mealById(n.mealId),show}} watchArt={watchArt} onChoose={()=>onReplay(n)} focusKey={'replay'+n.id} label="YOUR FAVORITE"/>:null;})}</Rail>}
 {!!catalogError&&<View style={b.empty}><Text style={b.small}>{catalogError}</Text><Button onPress={()=>setRetry(v=>v+1)}>Reload catalog</Button></View>}
 <View style={[b.footer,{margin:wide?52:20,marginTop:10}]}><Text style={b.h2}>Make the evening yours</Text><View style={b.actions}><Button onPress={onPantry}>Use my pantry</Button><Button onPress={onGroup}>Plan together</Button><Button onPress={onAI}>Ask the concierge</Button><Button onPress={()=>onSearch('food')}>Start with dinner</Button><Button onPress={onSurprise}>Surprise us</Button></View></View>
 </BrowseScroll>;
}
export function PairingComparison({discovery,message,source,receipt,picks,prefs,region,watchArt,mealArt,onChoose,onBack,onDetails,refinements}:any){const {width}=useWindowDimensions(),wide=width>=1100,sameTitle=picks.length&&picks.every((p:any)=>p.show.id===picks[0].show.id);return <BrowseScroll memoryKey="pair-comparison" contentContainerStyle={{padding:width<900?20:48,paddingBottom:60}}><Button quiet style={{alignSelf:'flex-start'}} onPress={onBack}>← Your preferences</Button><Text style={[b.h2,{marginTop:24,fontSize:width<900?36:48,lineHeight:width<900?44:58}]}>{sameTitle?picks[0].show.name:discovery?'Something a little different':'Choose your evening'}</Text><Text style={[b.meta,{marginBottom:28}]}>{sameTitle?'Choose a dinner, then review ingredients or find similar takeout.':prefs.people+' people · '+prefs.diet+' · Up to '+prefs.cookTime+'m cooking'}</Text>{!picks.length?<View style={b.empty}><Text style={b.description}>{message||'No dinners fit these limits. Adjust your preferences or try another match.'}</Text></View>:<View style={{flexDirection:wide?'row':'column',gap:24,alignItems:'stretch'}}>{picks.map((p:any,i:number)=><View key={p.meal.id+p.show.id} style={[b.comparison,{flex:wide?1:undefined}]}><RecipeArt meal={p.meal} style={{height:wide?210:240,width:'100%'}}/><View style={{padding:24,flex:1}}><Text style={[b.kicker,{fontSize:18}]}>{p.eveningStyle||'DINNER '+(i+1)}</Text>{!sameTitle&&<Text style={b.small}>{p.show.name}</Text>}<Text style={[b.foodName,{color:'#fff',minHeight:wide?80:undefined}]}>{p.meal.name}</Text><Text style={b.meta}>{p.meal.minutes}m cook · {p.show.minutes}m watch</Text><ConnectionBadge pair={p}/><PairingReason pair={p}/><Button primary focusKey={'pick'+p.meal.id+p.show.id} onPress={()=>onChoose(p,'cook')}>Review dinner →</Button><Button quiet focusKey={'info'+p.meal.id+p.show.id} style={{marginTop:12}} onPress={()=>onDetails(p)}>Why this pairing?</Button></View></View>)}</View>}{refinements}<DecisionReceipt receipt={receipt}/>{sameTitle&&<AvailabilityBadge show={picks[0].show} region={region}/>}</BrowseScroll>;}
const b=StyleSheet.create({household:{paddingHorizontal:52,paddingVertical:16,flexDirection:'row',flexWrap:'wrap',alignItems:'center',justifyContent:'space-between',gap:12},hero:{overflow:'hidden'},heroLayout:{padding:52,gap:42,alignItems:'center'},heroTitle:{color:'#fff',fontWeight:'900',letterSpacing:-1.5,marginVertical:14},heroMeal:{fontSize:32,color:'#FFC0A3',fontWeight:'800',marginBottom:14},kicker:{color:'#C6D1FF',fontSize:18,fontWeight:'900',letterSpacing:2.3,marginBottom:10},meta:{color:'#E8EDF5',fontSize:28,lineHeight:38,marginVertical:7,fontWeight:'600'},small:{color:'#C8D1DE',fontSize:24,lineHeight:34},description:{color:'#F0F3F8',fontSize:23,lineHeight:34,marginVertical:14},actions:{flexDirection:'row',flexWrap:'wrap',gap:16,marginVertical:18},rail:{paddingLeft:52,marginBottom:44},h2:{color:'#fff',fontSize:38,lineHeight:46,fontWeight:'800',marginBottom:14},h3:{color:'#fff',fontSize:32,lineHeight:40,fontWeight:'800',textShadowColor:'#000',textShadowRadius:8},episode:{color:'#E2E7EF',fontSize:18,lineHeight:25,marginTop:4},foodName:{color:'#FFC0A3',fontSize:30,lineHeight:40,fontWeight:'800'},copy:{padding:19,backgroundColor:'#0D131E'},copyRest:{paddingVertical:15},cardTitleOverlay:{position:'absolute',left:18,right:156,bottom:16},focusHint:{color:'#EEF3FF',fontSize:18,fontWeight:'800',marginTop:7},eveningCard:{width:420,gap:10,minHeight:310},infoButton:{alignSelf:'stretch',justifyContent:'center',minHeight:58},smallDish:{position:'absolute',right:14,bottom:12,width:122,height:98,borderRadius:12,borderWidth:2,borderColor:'#ffffff88'},cardBadge:{position:'absolute',left:12,top:12,backgroundColor:'#05070BEF',color:'#fff',paddingHorizontal:12,paddingVertical:8,borderRadius:18,fontSize:20,fontWeight:'900',letterSpacing:.8},hubs:{flexDirection:'row',flexWrap:'wrap',gap:14,paddingHorizontal:52,marginBottom:38},footer:{margin:52,padding:36,backgroundColor:'#111A29',borderRadius:18},empty:{padding:52,gap:16},availability:{paddingVertical:14,minHeight:64},availabilityText:{color:'#C8D4FF',fontSize:20,lineHeight:29},comparison:{backgroundColor:'#0F1622',borderRadius:18,overflow:'hidden',borderWidth:2,borderColor:'#45597A'},progress:{height:5,backgroundColor:'#304264',marginTop:10,borderRadius:3}});



