import {Text} from './TVText';
import React,{useContext,useEffect,useRef,useState} from 'react';
import {Animated,View,StyleSheet} from 'react-native';
import {TVButton as Button} from './TVButton';
import {RecipeArt} from './RecipeArt';
import {MotionContext} from './Motion';
import {mealById,showById} from './catalog/catalog';
import {ingredients} from './catalog/engine';
import {api} from './api';
import {BrandMark} from './Brand';
export function TasteTwin({house,onOpen}:any){const nights=house?.nights||[],memory=house?.memory||{},rated=nights.filter((n:any)=>n.feedback),mealCounts=new Map<string,number>(),moodCounts=new Map<string,number>();for(const night of nights){const meal=mealById(night.mealId);if(meal?.cuisine)mealCounts.set(meal.cuisine,(mealCounts.get(meal.cuisine)||0)+1);if(night.prefs?.mood)moodCounts.set(night.prefs.mood,(moodCounts.get(night.prefs.mood)||0)+1);}const top=(map:Map<string,number>)=>[...map.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0],avg=nights.length?Math.round(nights.reduce((sum:number,n:any)=>sum+(mealById(n.mealId)?.minutes||0),0)/nights.length):null,signals=[['STORY ENERGY',memory.preferredMood||top(moodCounts)||'Still learning'],['FLAVOR HOME',memory.favoriteCuisines?.[0]||top(mealCounts)||'Still learning'],['COOKING RHYTHM',memory.preferredEffort==='Easy'?'Easy first':avg?`About ${avg} minutes`:'Still learning'],['WATCH SHAPE',memory.shorter?'Short episodes':'Flexible runtime']];return <View style={s.twin}><View style={s.twinHead}><View style={s.twinMark}><BrandMark size={76}/><View style={s.twinLive}/></View><View style={{flex:1}}><Text style={s.tag}>YOUR HOUSEHOLD TASTE TWIN</Text><Text style={s.hero}>{rated.length>=3?'Calibrated to your evenings.':rated.length?'Learning with every rating.':'Ready to learn your rhythm.'}</Text><Text style={s.body}>Built only from saved preferences and evenings you rated. It explains recommendation boosts without inventing a personality profile.</Text></View><Text style={s.twinCount}>{String(rated.length).padStart(2,'0')}<Text style={s.twinCountLabel}>{`\n`}RATED</Text></Text></View><View style={s.twinGrid}>{signals.map(([label,value],index)=><View key={label} style={[s.twinSignal,{borderColor:['#6E8EFF','#FFA47E','#78DBB5','#C778C8'][index]}]}><Text style={s.twinLabel}>{label}</Text><Text style={s.twinValue}>{value}</Text></View>)}</View><Button onPress={onOpen}>Review or remove what Crave Frame remembers →</Button></View>}
export function TasteMemory({house,onUpdate}:any){const [busy,setBusy]=useState(false),[error,setError]=useState('');const m=house.memory||{};const entries:any[]=[];if(m.shorter)entries.push({field:'shorter',label:'You prefer episodes under 45 minutes'});if(m.preferredMood)entries.push({field:'preferredMood',label:'You prefer a '+m.preferredMood.toLowerCase()+' mood'});if(m.preferredEffort==='Easy')entries.push({field:'preferredEffort',label:'You prefer easier cooking'});for(const field of ['favoriteMeals','favoriteCuisines','dislikedIngredients','dislikedPairs','watched'])for(const value of m[field]||[]){let label=field==='favoriteMeals'?'You liked '+(mealById(value)?.name||value):field==='favoriteCuisines'?'You prefer '+value+' cuisine':field==='dislikedIngredients'?'Avoid '+value:field==='watched'?'Already watched: '+(house.titles?.find((t:any)=>t.id===value)?.name||showById(value)?.name||value):'You disliked the pairing '+value;entries.push({field,value,label});}return <View style={s.panel}><Text style={s.title}>What shapes your recommendations</Text><Text style={s.body}>These saved preferences affect your next choices. Remove one to stop using it; your saved evenings remain.</Text>{!entries.length&&<Text style={s.body}>No taste preferences saved yet. Rate an evening to teach us what you enjoy.</Text>}{entries.map(e=><View key={e.field+e.value} style={s.row}><Text style={[s.body,{flex:1}]}>{e.label}</Text><Button disabled={busy} onPress={async()=>{setBusy(true);setError('');try{onUpdate(await api('memory','PATCH',{field:e.field,value:e.value}));}catch(e){setError(e.message);}finally{setBusy(false);}}}>Remove</Button></View>)}{!!error&&<Text style={s.body}>{error}</Text>}</View>;}
export function ChangeComparison({night,rescue,adapted}:any){
 const reduced=useContext(MotionContext),motion=useRef(new Animated.Value(reduced?1:0)).current;
 useEffect(()=>{if(reduced){motion.setValue(1);return;}Animated.timing(motion,{toValue:1,duration:720,useNativeDriver:true}).start();},[rescue.choice.mealId,reduced]);
 const old=mealById(night.mealId),next=mealById(rescue.choice.mealId),before=ingredients(old,night.prefs.people,night.adapted),after=ingredients(next,rescue.request.people,adapted),start=Math.max(night.planStart||Date.parse(night.created),Date.now())+rescue.request.delay*60000,dinner=night.dinnerMinutes||25,watch=night.show||showById(night.showId);const time=(n:number)=>new Date(n).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
 const changes=[
  {label:'WATCH',before:watch.name,after:rescue.choice.showName,kept:!rescue.request.allowWatchChange},
  {label:'SERVINGS',before:String(night.prefs.people),after:String(rescue.request.people),kept:night.prefs.people===rescue.request.people},
  {label:'COOKING',before:old.minutes+' min',after:next.minutes+' min',kept:old.minutes===next.minutes},
  {label:'RECIPE STEPS',before:String(old.steps.length),after:String(next.steps.length),kept:old.steps.length===next.steps.length},
  {label:'TOTAL EVENING',before:old.minutes+dinner+watch.minutes+' min',after:rescue.choice.total+' min',kept:false},
 ];
 return <View style={s.panel}><Text style={s.tag}>YOUR REQUEST, MADE CONCRETE</Text><Text style={s.hero}>Watch the plan transform.</Text><Text style={s.body}>{rescue.choice.aiExplained?'AI compared the eligible recipes and preserved your hard limits.':'Catalog rules selected this alternative.'} Nothing changes until you approve it.</Text>
  <View style={s.transform}><Animated.View style={[s.mealCard,{opacity:motion.interpolate({inputRange:[0,1],outputRange:[1,.5]})}]}><RecipeArt meal={old} style={s.art}/><Text style={s.tag}>BEFORE</Text><Text style={s.title}>{old.name}</Text></Animated.View><Animated.View style={[s.arrow,{opacity:motion}]}><Text style={s.arrowText}>→</Text><Text style={s.changed}>AI CHANGED</Text></Animated.View><Animated.View style={[s.mealCard,s.afterCard,{opacity:motion,transform:[{translateX:motion.interpolate({inputRange:[0,1],outputRange:[55,0]})}]}]}><RecipeArt meal={next} style={s.art}/><Text style={s.tag}>AFTER</Text><Text style={s.title}>{next.name}</Text></Animated.View></View>
  <View style={s.changeGrid}>{changes.map(x=><View key={x.label} style={s.changeRow}><View style={{flex:1}}><Text style={s.tag}>{x.label}</Text><Text numberOfLines={2} style={s.before}>{x.before}</Text></View><Text style={s.inlineArrow}>→</Text><View style={{flex:1}}><Text style={[s.state,{color:x.kept?'#78DBB5':'#FFA47E'}]}>{x.kept?'PRESERVED':'REVISED'}</Text><Text numberOfLines={2} style={s.after}>{x.after}</Text></View></View>)}</View>
  {rescue.choice.evidence?.map((fact:string)=><Text key={fact} style={s.body}>✓ {fact}</Text>)}{!!rescue.choice.decisionReason&&<Text style={s.reason}>{rescue.choice.decisionReason}</Text>}{!!rescue.choice.decisionTradeoff&&<Text style={s.tradeoff}>Tradeoff: {rescue.choice.decisionTradeoff}</Text>}
  <Text style={s.tag}>INGREDIENT DELTA</Text><View style={s.ingredients}>{after.map(i=>{const previous=before.find(o=>o.name===i.name);return <Text key={i.name} style={s.ingredient}>{previous?'↗':'＋'} {i.name} · {previous?previous.amount+' '+previous.unit+' → ':''}{i.amount} {i.unit}</Text>;})}{before.filter(i=>!after.some(o=>o.name===i.name)).map(i=><Text key={i.name} style={[s.ingredient,{color:'#E2A99E'}]}>− Remove {i.name}</Text>)}</View>
  <Text style={s.body}>Revised start {time(start)} · estimated finish {time(start+rescue.choice.total*60000)}. Cooking times are recipe estimates; larger batches may take longer.</Text>
 </View>;
}
const s=StyleSheet.create({panel:{padding:24,marginVertical:18,borderRadius:18,backgroundColor:'#111A2B',borderColor:'#43536E',borderWidth:1},twin:{padding:26,marginVertical:18,borderRadius:20,backgroundColor:'#0B1424F2',borderColor:'#566E9B',borderWidth:1},twinHead:{flexDirection:'row',alignItems:'center',gap:20},twinMark:{width:84,height:84,alignItems:'center',justifyContent:'center'},twinLive:{position:'absolute',right:1,bottom:5,width:14,height:14,borderRadius:7,backgroundColor:'#78DBB5',borderWidth:3,borderColor:'#0B1424'},twinCount:{color:'#6E8EFF',fontSize:43,fontWeight:'900',textAlign:'center'},twinCountLabel:{color:'#9DABC0',fontSize:10,fontWeight:'900',letterSpacing:1.2},twinGrid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginVertical:20},twinSignal:{flex:1,minWidth:180,padding:16,borderRadius:12,borderLeftWidth:3,backgroundColor:'#111D30'},twinLabel:{color:'#91A1B8',fontSize:11,fontWeight:'900',letterSpacing:1.3},twinValue:{color:'#F5F7F2',fontSize:18,fontWeight:'800',marginTop:7},hero:{color:'#fff',fontSize:30,lineHeight:38,fontWeight:'800',marginVertical:8},title:{color:'#fff',fontSize:22,fontWeight:'800',marginVertical:8},body:{color:'#c5d0e3',fontSize:16,lineHeight:24,marginVertical:6},row:{flexDirection:'row',flexWrap:'wrap',gap:18,alignItems:'center'},tag:{color:'#FFA47E',fontSize:13,fontWeight:'800',letterSpacing:1.4,marginTop:8},transform:{flexDirection:'row',alignItems:'center',gap:16,marginVertical:22},mealCard:{flex:1,minWidth:200,backgroundColor:'#172132',borderRadius:16,overflow:'hidden',paddingBottom:14},afterCard:{borderColor:'#FFA47E',borderWidth:1,backgroundColor:'#1A2030'},art:{width:'100%',height:145},arrow:{width:88,alignItems:'center'},arrowText:{color:'#FFA47E',fontSize:46,fontWeight:'300'},changed:{color:'#AFC0D7',fontSize:10,fontWeight:'900',letterSpacing:1,textAlign:'center'},changeGrid:{borderTopWidth:1,borderColor:'#32415A',marginBottom:16},changeRow:{flexDirection:'row',alignItems:'center',gap:14,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#27354B'},before:{color:'#AAB5C5',fontSize:17,marginTop:5},after:{color:'#FFF',fontSize:18,fontWeight:'700',marginTop:5},inlineArrow:{color:'#71819B',fontSize:23},state:{fontSize:11,fontWeight:'900',letterSpacing:1.2},reason:{color:'#E9EEF6',fontSize:18,lineHeight:27,marginVertical:12},tradeoff:{color:'#E9BA9D',fontSize:16,lineHeight:24,marginBottom:14},ingredients:{flexDirection:'row',flexWrap:'wrap',gap:8,marginVertical:12},ingredient:{color:'#CDE6DA',fontSize:15,backgroundColor:'#18283A',paddingHorizontal:12,paddingVertical:8,borderRadius:16}});
