import {Text} from './TVText';
import React,{useEffect,useRef,useState} from 'react';
import {Platform,View} from 'react-native';
import {TVButton as Button} from './TVButton';
export function mainPanel(doc:any=document){if(doc.querySelector('[aria-modal="true"], [data-testid="phone-dialog"]'))return null;return [...doc.querySelectorAll('[data-testid="main-scroll"]')].find((el:any)=>{const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&el.scrollHeight>el.clientHeight+1;}) as HTMLElement|undefined;}
export function scrolledPanels(doc:any=document){const panel=mainPanel(doc);return panel&&panel.scrollTop>0?[panel]:[];}
export function backToTop(doc:any=document){const panels=scrolledPanels(doc);if(!panels.length)return false;panels.forEach(el=>{el.scrollTop=0;});const menu=doc.querySelector('[data-testid="remote-row-navigation"] [role="button"]')||doc.querySelector('[role="button"]');menu?.focus({preventScroll:true});return panels.length>0;}
export function pageUp(doc:any=document){const panels=scrolledPanels(doc);const panel=panels[0];if(!panel)return false;panel.scrollTop=Math.max(0,panel.scrollTop-Math.max(180,panel.clientHeight*.75));const rect=panel.getBoundingClientRect(),height=doc.defaultView?.innerHeight||10000;const visible=[...panel.querySelectorAll<HTMLElement>('[role="button"]')].filter(el=>{const r=el.getBoundingClientRect();return !el.closest('[data-testid="silk-scroll-assist"]')&&el.getAttribute('aria-disabled')!=='true'&&r.width>0&&r.top>=Math.max(rect.top,0)&&r.bottom<=Math.min(rect.bottom,height);});if(!doc.activeElement?.closest?.('[data-testid="silk-scroll-assist"]'))visible[0]?.focus({preventScroll:true});return true;}
export function pageDown(doc:any=document){const panel=mainPanel(doc);if(!panel)return false;const next=Math.min(panel.scrollHeight-panel.clientHeight,panel.scrollTop+Math.max(180,panel.clientHeight*.75));if(next<=panel.scrollTop+1)return false;panel.scrollTop=next;return true;}
export function SilkScrollAssist(){const [visible,setVisible]=useState(false),[down,setDown]=useState(false),frame=useRef<any>(null);useEffect(()=>{if(Platform.OS!=='web')return;const update=()=>{if(frame.current!==null)return;frame.current=requestAnimationFrame(()=>{frame.current=null;const panels=scrolledPanels();setVisible(panels.some(p=>p.scrollTop>1));const panel=mainPanel();setDown(!!panel&&panel.scrollTop+panel.clientHeight<panel.scrollHeight-1);});};document.addEventListener('scroll',update,true);window.addEventListener('resize',update);document.addEventListener('load',update,true);const observer=new MutationObserver(update);observer.observe(document.body,{childList:true,subtree:true});update();return()=>{document.removeEventListener('scroll',update,true);window.removeEventListener('resize',update);document.removeEventListener('load',update,true);observer.disconnect();if(frame.current!==null)cancelAnimationFrame(frame.current);};},[]);if(Platform.OS!=='web')return null;return <View testID="silk-scroll-assist" style={{flexDirection:'row',flexWrap:'wrap',justifyContent:'flex-end',alignItems:'center',gap:10,paddingHorizontal:24,paddingVertical:4,backgroundColor:'#0C1625',borderTopWidth:2,borderColor:'#576E8C',flexShrink:0}}><Text style={{color:'#DCE8F8',fontSize:22,marginRight:12}}>Scroll</Text><Button compact disabled={!down} focusKey="silk-page-down" onPress={()=>pageDown()}>↓ Page down</Button><Button compact disabled={!visible} focusKey="silk-page-up" onPress={()=>pageUp()}>↑ Page up</Button><Button disabled={!visible} focusKey="silk-top" onPress={()=>{backToTop();setVisible(false);}}>↑ Back to top</Button></View>;}
