import {mealPhoto} from './meal-photos.js';
import {meals,mealById,defaults,moods} from './catalog.js';
import {artworkFor,tmdbImage} from './artwork.js';
import {foodPreferences} from './diets.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const food=mealPhoto;
const poster=s=>artworkFor(s)?.image||'/app/images/'+s.scene+'.png';
const samples=['Two people, chicken tacos and an adventurous movie. 30 minutes to cook, up to 3 hours to watch.','A cozy date night. We have pasta and tomatoes. Keep cooking under 30 minutes.','We disagree: one wants comfort, one wants adventure. Find common ground.'];
export function createAiUI(ctx){
 const state={mode:'plan',prompt:'',response:null,pending:false,error:'',image:null,preview:'',pin:null};
 const button=(label,action,attrs='',cls='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
 const modes=[['plan','✦','Plan tonight'],['pantry','◉','See my pantry'],['rescue','↺','Rescue the night'],['coach','☷','Cooking coach'],['taste','♡','My taste']];
 const summary=p=>`<div class="ai-constraints"><span>${p.people} people</span><span>${esc(p.mood)}</span><span>${p.cookTime} min cook</span><span>${p.watchTime} min watch</span><span>${esc(p.diet)}</span></div>`;
 function home(){return `<section class="ai-entry"><div><span class="ai-mark">✦</span><p class="eyebrow">Meet your evening concierge</p><h2>Tell us the night.<br>We’ll bring it together.</h2><p>A meal, a movie, a fridge full of possibilities. Start with what you know.</p></div><div class="ai-entry-action"><label for="ai-home-prompt" class="field-label">What would make tonight great?</label><textarea id="ai-home-prompt" maxlength="1200" placeholder="Two people, something adventurous, and the chicken in our fridge…"></textarea>${button('Make a night of it <span>✦</span>','ai-home','','primary full')}<div class="ai-entry-links">${button('Start with a pantry photo','ai-open','data-mode="pantry"','text-btn')}${button('Explore the concierge →','ai-open','','text-btn')}</div></div></section>`;}
 function page(){const h=ctx.get().household,p=state.response?.prefs||ctx.get().draft.prefs||defaults;const saved=h?.nights||[];const nights=state.mode==='rescue'?saved.filter(n=>n.status==='planned'&&!n.watchStarted):saved;
 return `<section class="concierge"><div class="concierge-heading"><div><p class="eyebrow"><span class="ai-live-dot"></span> Your evening concierge</p><h1>A little less deciding.<br><em>A lot more evening.</em></h1></div><div class="concierge-note"><span>✦</span><p>Real recipes. Your kind of stories.<br>Thoughtfully brought together.</p></div></div><div class="concierge-layout"><aside class="ai-sidebar"><nav aria-label="AI features">${modes.map(([id,icon,label])=>button(`<span>${icon}</span>${label}`,'ai-mode',`data-mode="${id}" aria-pressed="${state.mode===id}"`,state.mode===id?'active':'')).join('')}</nav><div class="ai-sidebar-note"><p class="eyebrow">Your kitchen, remembered</p><strong>${h?.pantry?.length||0} ingredients</strong><p>${h?.memory?.favoriteMeals?.length||0} favorite meals · ${saved.filter(n=>n.feedback).length} evenings rated</p><a href="#kitchen">Edit your preferences →</a></div><small class="ai-disclosure">Independent Alexa+ experience simulation. Powered by Gemini on Vertex AI; no Alexa account connection.</small></aside><div class="ai-workspace"><section class="ai-composer"><div class="ai-composer-title"><span class="ai-mark">${modes.find(m=>m[0]===state.mode)[1]}</span><div><p class="eyebrow">${state.mode==='plan'?'Both ways in. One evening.':state.mode==='pantry'?'From fridge to film':state.mode==='rescue'?'Keep the evening, change the plan':state.mode==='coach'?'A second pair of hands':'Learning from your feedback'}</p><h2>${{plan:'What are we in the mood for?',pantry:'A photo. A few possibilities.',rescue:'Plans changed? We’re on it.',coach:'What can I help you cook?',taste:'Your nights are telling a story.'}[state.mode]}</h2></div></div>
 ${state.mode==='plan'?`${state.pin?'<p class="ai-pin">Starting with your selected '+(state.pin.showId?'watch':'meal')+'. '+button('Let AI choose both','ai-unpin','','text-btn')+'</p>':''}<label class="field-label" for="ai-prompt">A meal, a title, a mood—or a little of everything</label>`:''}
 ${state.mode==='pantry'?`<label class="ai-upload" for="ai-photo">${state.preview?`<img src="${state.preview}" alt="Your selected pantry photo">`:'<span class="upload-glyph">＋</span>'}<strong>${state.image?'Photo ready to review':'Add a food or pantry photo'}</strong><span>JPEG, PNG or WebP · use your phone camera</span><input id="ai-photo" type="file" accept="image/jpeg,image/png,image/webp"></label><p class="catalog-note">Your photo is sent to Google to identify visible ingredients. The app does not save the photo. You choose what goes into your pantry.</p>`:''}
 ${['rescue','coach'].includes(state.mode)?`<label class="field-label" for="ai-night">Which evening?</label><select id="ai-night">${nights.length?nights.map(n=>`<option value="${n.id}">${esc(mealById(n.mealId)?.name)} + ${esc(n.show?.name||'your watch')}</option>`).join(''):'<option value="">Plan and save an evening first</option>'}</select>`:''}
 ${!['pantry','taste'].includes(state.mode)?`<textarea id="ai-prompt" rows="3" maxlength="1200" placeholder="${state.mode==='rescue'?'We’re 20 minutes late and out of mushrooms. Keep the same movie.':state.mode==='coach'?'How can I tell when this step is ready?':samples[0]}">${esc(state.prompt)}</textarea>`:''}
 ${state.mode==='plan'?`<details class="ai-limits"><summary>Tonight’s limits · change before asking</summary><div class="ai-pref-grid">${select('ai-people','People',[1,2,3,4,5,6,7,8],p.people)}${select('ai-mood','Mood',moods,p.mood)}${select('ai-diet','Food preference',foodPreferences,p.diet)}${select('ai-cook','Cooking minutes',[15,30,45,60],p.cookTime)}${select('ai-watch','Viewing minutes',[30,45,90,120,180,240,360,600],p.watchTime)}</div><p class="catalog-note">AI respects your time and food limits. Mention changes in your request. Ingredient preferences do not verify allergy safety.</p></details>`:''}
 <div class="ai-send-row">${button(state.pending?'Bringing your evening together…':{plan:'Find our evening ✦',pantry:'Identify ingredients ✦',rescue:'Find a way to save tonight ✦',coach:'Ask the cooking coach ✦',taste:'Reflect on my taste ✦'}[state.mode],'ai-send',state.pending?'disabled':'','primary')}${!['pantry','taste'].includes(state.mode)?button('Speak','ai-voice','aria-label="Dictate your request"','voice-button'):''}<span id="ai-voice-status" role="status"></span></div>
 ${state.mode==='plan'&&!state.response?`<div class="ai-starters"><p class="eyebrow">A little inspiration</p>${samples.map((s,i)=>button(esc(s),'ai-sample',`data-index="${i}"`)).join('')}</div>`:''}</section>
 <div id="ai-response" aria-live="polite" aria-busy="${state.pending}">${state.pending?`<div class="ai-thinking"><span class="ai-spinner"></span><div><strong>${state.mode==='pantry'?'Looking at the ingredients…':'Considering your evening…'}</strong><p>Checking the details and bringing the choices together.</p></div></div>`:state.error?`<div class="ai-error"><strong>Let’s try that again.</strong><p>${esc(state.error)}</p><a href="#choose">Explore the catalog →</a></div>`:result(state.response)}</div></div></div></section>`;}
 function select(id,label,values,current){return `<label>${label}<select id="${id}">${values.map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
 function result(r){if(!r)return `<div class="ai-empty-state"><div class="ai-photo-strip"><img src="/app/images/tacos.png" alt="Tacos"><img src="/app/images/pasta.png" alt="Tomato pasta"><img src="/app/images/risotto.png" alt="Risotto"></div><div><p class="eyebrow">The possibilities are delicious</p><p>Find something to watch with dinner.<br>Or something to cook with your watch.</p></div></div>`;
 if(r.mode==='pantry')return `<section class="ai-answer"><p class="eyebrow">You have the final say</p><h2>Here’s what I can see.</h2><p>${esc(r.note)}</p><div class="ai-ingredient-grid">${r.ingredients.map(x=>`<label class="check-row"><input type="checkbox" data-ai-ingredient value="${esc(x)}" checked>${esc(x)}</label>`).join('')}</div>${r.uncertain?.length?'<p>Uncertain: '+esc(r.uncertain.join(', '))+'. Add these manually only if you can confirm them.</p>':''}<p>${esc(r.notice)}</p>${button('Approve selected ingredients','ai-save-pantry',r.ingredients.length?'':'disabled','primary')}${button('Plan with my pantry →','ai-pantry-plan','','text-btn')}</section>`;
 if(r.mode==='rescue')return `<section class="ai-answer"><p class="eyebrow">Nothing has changed yet</p><h2>A good night is still on.</h2><p>${esc(r.answer)}</p><div class="ai-constraints"><span>${r.request.delay} min delay</span><span>${r.request.people} people</span><span>${r.request.allowWatchChange?'Watch can change':'Keeping your watch'}</span></div>${r.request.missing.length?'<p>Missing: '+esc(r.request.missing.join(', '))+'</p>':''}${r.options.map((o,i)=>`<article class="ai-rescue-card"><img src="${food(mealById(o.mealId))}" alt="${esc(o.mealName)}"><div><h3>${esc(o.mealName)}</h3><p>With ${esc(o.showName)}</p><p>${esc(o.tradeoff)}</p><strong>${o.minutesSaved} min saved</strong>${button('Review this change →','ai-rescue-review',`data-index="${i}"`,'primary')}</div></article>`).join('')}</section>`;
 if(['coach','taste'].includes(r.mode))return `<section class="ai-answer"><p class="eyebrow">${r.mode==='coach'?'Alongside your recipe':'Based on your saved feedback'}</p><h2>${r.mode==='coach'?'Let’s make it work.':'More your kind of evening.'}</h2><p class="ai-answer-prose">${esc(r.answer)}</p><ul>${r.tips.map(t=>'<li>'+esc(t)+'</li>').join('')}</ul>${r.mode==='taste'?button('Plan with this memory →','ai-pantry-plan','','primary'):'<p class="catalog-note">Advice only. Your saved recipe and cooking steps have not changed.</p>'}</section>`;
 return `<section class="ai-plan-answer"><div class="ai-answer-heading"><p class="eyebrow">✦ Your evening, considered</p><h2>${esc(r.headline||'Let’s find your evening.')}</h2><p>${esc(r.answer)}</p>${r.prefs?summary(r.prefs):''}${r.avoid?.length?'<p>For this request, also avoiding: '+esc(r.avoid.join(', '))+'</p>':''}</div>${r.titleChoices?.map(x=>`<button class="catalog-result" data-action="catalog-detail" data-type="${x.type}" data-id="${x.id}">${tmdbImage(x.posterPath)?`<img class="search-poster" src="${tmdbImage(x.posterPath)}" alt="${esc(x.name)} poster">`:''}<strong>${esc(x.name)}</strong><span>${esc(x.year)} · ${x.type==='tv'?'TV series':'Movie'}</span></button>`).join('')||''}<div class="ai-pairings">${(r.picks||[]).map((p,i)=>`<article class="ai-pair-card"><div class="ai-pair-visual"><img class="ai-watch-image" src="${poster(p.show)}" alt="${esc(p.show.name)} artwork"><img class="ai-dish-image" src="${food(p.meal)}" alt="${esc(p.meal.name)}"><span class="ai-pick-number">0${i+1} / ${!p.aiExplained?'Catalog alternative':i===0?'Tonight’s first choice':'A different direction'}</span><div class="ai-watch-title"><span>${esc(p.show.kind)} · ${p.show.minutes} min</span><h3>${esc(p.show.name)}</h3></div></div><div class="ai-pair-copy"><p class="eyebrow">On your table</p><h3>${esc(p.meal.name)}</h3><div class="meta"><span>${p.meal.minutes} min</span><span>${esc(p.meal.effort)}</span><span>Serves ${r.prefs.people}</span></div><p class="ai-why">${esc(p.reason)}</p><div class="ai-tradeoff"><strong>The tradeoff</strong><p>${esc(p.tradeoff)}</p></div>${p.ritual?`<p class="ai-ritual">✦ ${esc(p.ritual)}</p>`:''}${button('Make this our night →','ai-pair',`data-index="${i}"`,i===0?'primary full':'full')}</div></article>`).join('')}</div>${r.picks?.length?'<p class="catalog-note">AI explains the creative connection; recipes and runtimes come from the catalog. Inspiration does not mean the dish appears in the story. Review ingredients before cooking. Streaming is not included.</p>':''}</section>`;
 }
 function keepPrompt(){const el=document.querySelector('#ai-prompt');if(el)state.prompt=el.value;}
 async function send(){keepPrompt();state.error='';const mode=state.mode,nightId=document.querySelector('#ai-night')?.value;
 const prefs={...(state.response?.prefs||ctx.get().draft.prefs)};for(const [id,k] of [['ai-people','people'],['ai-mood','mood'],['ai-diet','diet'],['ai-cook','cookTime'],['ai-watch','watchTime']]){const el=document.getElementById(id);if(el)prefs[k]=['people','cookTime','watchTime'].includes(k)?Number(el.value):el.value;}
 if(mode==='pantry'&&!state.image){state.error='Choose a food photo first.';ctx.render();return;}
 state.pending=true;ctx.render();
 try{const response=await ctx.api('ai','POST',{mode,prompt:state.prompt,prefs,nightId,image:mode==='pantry'?state.image:undefined,...state.pin});state.response=response;state.response.nightId=nightId;await ctx.refresh();}
 catch(e){state.error=e.message;}finally{state.pending=false;ctx.render();document.querySelector('#ai-response')?.scrollIntoView({behavior:'smooth',block:'start'});}
 }
 const actions={
  'ai-open':el=>{state.mode=el.dataset.mode||'plan';state.pin=el.dataset.pin?ctx.pin():null;state.prompt='';state.response=null;state.error='';ctx.go('concierge');},
  'ai-home':async()=>{state.mode='plan';state.prompt=document.querySelector('#ai-home-prompt')?.value||'';state.response=null;state.pin=null;ctx.go('concierge');if(state.prompt){await new Promise(r=>setTimeout(r,50));await send();}},
  'ai-mode':el=>{if(state.pending)return;state.mode=el.dataset.mode;state.prompt='';state.response=null;state.error='';ctx.render();},
  'ai-unpin':()=>{state.pin=null;ctx.render();},
  'ai-sample':el=>{state.prompt=samples[Number(el.dataset.index)];ctx.render();document.querySelector('#ai-prompt')?.focus();},
  'ai-send':send,
  'ai-pair':el=>{const r=state.response;ctx.select(r.picks[Number(el.dataset.index)],r.prefs);},
  'ai-save-pantry':async()=>{const values=[...document.querySelectorAll('[data-ai-ingredient]:checked')].map(el=>el.value);if(!values.length)throw Error('Select at least one ingredient.');const names=[...new Set(meals.flatMap(m=>m.ingredients.map(i=>i[0])))];const normalized=values.map(v=>names.find(n=>n.toLowerCase()===v.toLowerCase())||v);await ctx.api('pantry','PUT',{items:[...new Set([...(ctx.get().household.pantry||[]),...normalized])].slice(0,60)});await ctx.refresh();ctx.toast('Confirmed ingredients saved to your kitchen.');},
  'ai-pantry-plan':()=>{state.mode='plan';state.prompt='Plan an evening using my saved pantry and taste preferences.';state.response=null;state.error='';state.pin=null;ctx.render();},
  'ai-rescue-review':el=>ctx.rescue(state.response,Number(el.dataset.index)),
  'ai-voice':()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){ctx.toast('Voice dictation is not supported in this browser. You can type your request.');return;}const r=new Recognition();r.lang='en-US';r.interimResults=false;const status=document.querySelector('#ai-voice-status');status.textContent='Listening…';r.onresult=e=>{state.prompt=e.results[0][0].transcript;document.querySelector('#ai-prompt').value=state.prompt;status.textContent='Ready to review and send';};r.onerror=()=>{status.textContent='Could not hear you. Try again or type.';};r.onend=()=>{if(status.textContent==='Listening…')status.textContent='Microphone stopped';};r.start();},
 };
 document.addEventListener('change',async e=>{if(e.target.id!=='ai-photo')return;const file=e.target.files[0];if(!file)return;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12000000)throw Error('Choose a JPEG, PNG or WebP photo under 12 MB.');const bitmap=await createImageBitmap(file),scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/jpeg',0.8);if(data.length>1350000)throw Error('This photo is too large. Crop it and try again.');state.image={mimeType:'image/jpeg',data:data.split(',')[1]};state.preview=data;state.error='';state.response=null;ctx.render();}catch(error){ctx.toast(error.message);}});
 return {page,home,actions};
}
