const app=document.querySelector('#app'),status=document.querySelector('#status');
const key=new URLSearchParams(location.search).get('key');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,identified=null,items='',busy=false,enough=new Set(),checked=new Set(),editing=false,selectedStrategy='',provider='',etaMinutes=35;
async function api(action='',body){const c=new AbortController(),timer=setTimeout(()=>c.abort(),action==='identify'?55000:20000);try{const r=await fetch('/api/companion-link/'+encodeURIComponent(key||'')+(action?'/'+action:''),{method:body?'POST':'GET',headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:c.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not connect.');return d;}catch(e){if(e.name==='AbortError')throw Error('The connection timed out. Retry or enter ingredients manually.');throw e;}finally{clearTimeout(timer);}}
async function run(fn){if(busy)return;busy=true;status.textContent='Updating your evening…';app.setAttribute('aria-busy','true');app.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();status.textContent='';}catch(e){status.textContent=e.message;}finally{busy=false;app.setAttribute('aria-busy','false');app.querySelectorAll('button').forEach(b=>b.disabled=false);}}
const lines=s=>[...new Set(s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];
function pantry(){app.innerHTML=`<div class="eyebrow">PANTRY → TONIGHT</div><h1>A good evening starts in your kitchen.</h1><p>Scan what you have, check the ingredient names, then send them to your TV.</p><div class="panel"><div class="step">01 · SCAN OR TYPE</div><label class="file">Take a photo or choose one<input id="photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"></label><p class="note">Your photo is sent to Google for ingredient recognition and is not stored by Crave Frame. You approve the names before anything changes.</p>${identified?`<h2>Review what we spotted</h2>${[...(identified.ingredients||[]).map(name=>({name,certain:true})),...(identified.uncertain||[]).map(name=>({name,certain:false}))].map((i,n)=>`<label class="row"><input type="checkbox" data-found="${n}" value="${esc(i.name)}" ${i.certain?'checked':''}><span>${esc(i.name)}${!i.certain?'<small>Uncertain · include only if correct</small>':''}</span></label>`).join('')}<button id="add">Add checked ingredients below</button><p class="note">${esc(identified.note||'')}</p>`:''}</div><div class="panel"><div class="step">02 · CONFIRM YOUR PANTRY</div><h2>Edit ingredient names</h2><p>One ingredient per line. Existing pantry items are included; remove anything you no longer have.</p><label class="sr" for="ingredients">Pantry ingredient names</label><textarea id="ingredients" maxlength="5000">${esc(items)}</textarea><p class="note">Names don’t confirm quantities or freshness. Check packages for food restrictions.</p><button id="reload-pantry">Reload pantry (replaces this draft)</button><button class="primary" id="confirm">Confirm pantry & find three evenings →</button></div><p class="note">This private link can update your pantry for one hour. Keep the pantry screen open on your TV.</p>`;
 document.querySelector('#reload-pantry').onclick=()=>run(async()=>{identified=null;await load();});
 document.querySelector('#ingredients').addEventListener('input',e=>items=e.target.value);
 document.querySelector('#photo').addEventListener('change',e=>{const f=e.target.files[0];if(f)run(async()=>{status.textContent='Identifying ingredients…';const image=await prepare(f);identified=await api('identify',{image});pantry();});});
 document.querySelector('#add')?.addEventListener('click',()=>{items=[...new Set([...lines(items),...[...app.querySelectorAll('[data-found]:checked')].map(x=>x.value)])].join('\n');identified=null;pantry();});
 document.querySelector('#confirm').addEventListener('click',()=>run(async()=>{if(identified)throw Error('Add the checked photo ingredients, or uncheck and add none, before confirming.');const names=lines(items);if(names.length>60||names.some(n=>n.length>80))throw Error('Use up to 60 names, under 80 characters each.');const saved=await api('confirm',{items:names,revision:data.revision});data={...data,...saved};app.innerHTML='<div class="success">✓</div><div class="eyebrow">SENT TO YOUR TV</div><h1>Your pantry is ready for tonight.</h1><p>Your TV is finding pairings using your confirmed ingredients and evening limits.</p><div class="panel"><h2>'+names.length+' ingredients confirmed</h2><p>'+names.map(esc).join(' · ')+'</p><button id="again">Edit pantry</button></div>';document.querySelector('#again').onclick=pantry;}));
}
async function prepare(file){if(file.size>15000000)throw Error('Choose a photo smaller than 15 MB.');const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.78).split(',')[1];if(data.length>1350000)throw Error('Try a closer or smaller photo.');return {mimeType:'image/jpeg',data};}finally{bitmap.close();}}
const amount=i=>`${Number(i.amount.toFixed(2))} ${i.unit}`;
const storageKey=()=> 'cf-shopping-'+key+'-'+data.signature;
function storeChecked(){try{localStorage.setItem(storageKey(),JSON.stringify([...checked]));}catch{}}
function shopping(){const review=editing||!data.approved,list=review?data.items:data.missing;app.innerHTML=`<div class="eyebrow">${review?'CHECK THE KITCHEN':'READY FOR THE SHOP'}</div><h1>${review?'Only buy what’s missing.':'Your dinner, aisle by aisle.'}</h1><p>${esc(data.meal)}${data.show?' · '+esc(data.show):''}</p><span class="pill">Approved plan · ${data.people} servings</span>${review?`<p>Check each ingredient you have <strong>enough of for ${data.people} people</strong>. Everything left unchecked goes on your shopping list.</p><div class="panel">${list.map((i,n)=>`<label class="row"><input data-enough="${n}" type="checkbox" ${enough.has(i.name)?'checked':''}><span>${esc(i.name)}<small>${esc(amount(i))}${i.pantryListed?' · In saved pantry; check quantity':''}</small></span></label>`).join('')}</div><button class="primary" id="save">Create missing-ingredient list →</button>`:`<p>${list.length} ingredients to buy · ${data.enough.length} already covered</p><div class="progress"><i style="width:${list.length?100*list.filter(i=>checked.has(i.name)).length/list.length:100}%"></i></div>${!list.length?'<div class="panel"><h2>Your kitchen has it covered.</h2><p>No missing ingredients in this approved list.</p></div>':[...new Set(list.map(i=>i.section))].map(group=>`<section class="panel"><h2>${esc(group)}</h2>${list.filter(i=>i.section===group).map(i=>`<label class="row ${checked.has(i.name)?'done':''}"><input data-buy="${data.items.findIndex(x=>x.name===i.name)}" type="checkbox" ${checked.has(i.name)?'checked':''}><span>${esc(i.name)}<small>${esc(amount(i))}</small></span></label>`).join('')}</section>`).join('')}<div class="actions"><button id="edit">Review pantry quantities</button><button id="share">Share list</button></div><p class="note">Shopping checkmarks stay on this phone. Changes to the recipe or servings require a fresh ingredient review.</p>`}<button id="refresh">Refresh approved plan</button><p class="note">This link expires in seven days. Anyone with it can review and change this evening’s shopping list.</p>`;
 app.querySelectorAll('[data-enough]').forEach(x=>x.onchange=()=>{editing=true;const name=data.items[Number(x.dataset.enough)].name;x.checked?enough.add(name):enough.delete(name);});
 app.querySelectorAll('[data-buy]').forEach(x=>x.onchange=()=>{const name=data.items[Number(x.dataset.buy)].name;x.checked?checked.add(name):checked.delete(name);storeChecked();x.closest('label').classList.toggle('done',x.checked);app.querySelector('.progress i').style.width=(100*data.missing.filter(i=>checked.has(i.name)).length/data.missing.length)+'%';});
 document.querySelector('#save')?.addEventListener('click',()=>run(async()=>{data=await api('confirm',{signature:data.signature,revision:data.revision,enough:[...enough]});editing=false;shopping();}));
 document.querySelector('#edit')?.addEventListener('click',()=>{editing=true;enough=new Set(data.enough);shopping();});
 document.querySelector('#share')?.addEventListener('click',()=>run(async()=>{const text=`${data.meal} · ${data.people} servings\n`+data.missing.map(i=>`${i.section} · ${i.name}: ${amount(i)}`).join('\n');if(navigator.share){try{await navigator.share({title:'Crave Frame shopping list',text});}catch(e){if(e.name!=='AbortError')throw e;}}else if(navigator.clipboard){await navigator.clipboard.writeText(text);document.querySelector('#share').textContent='Copied ✓';}else throw Error('Sharing is unavailable in this browser. You can select and copy the list.');}));
 document.querySelector('#refresh').onclick=()=>run(load);
}
function order(){
 if(data.confirmation){const c=data.confirmation,name=c.provider==='ubereats'?'Uber Eats':'DoorDash';app.innerHTML=`<div class="success">✓</div><div class="eyebrow">SENT TO YOUR TV</div><h1>Your order is marked as placed.</h1><p>${esc(data.meal)} · ${esc(data.show)}</p><div class="panel receipt"><div><small>PROVIDER</small><strong>${name}</strong></div><div><small>ESTIMATED ARRIVAL</small><strong>${new Date(c.placedAt+c.etaMinutes*60000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</strong></div><div><small>SEARCH USED</small><strong>${esc(c.query)}</strong></div><div><small>BUDGET GUIDE</small><strong>${esc(c.budget)}</strong></div></div><p>Your television is updating the dinner and watch schedule. Use ${name} for payment, restaurant messages, and live tracking.</p>`;return;}
 selectedStrategy=selectedStrategy||data.selectedStrategy||data.strategies[0].id;const chosen=data.strategies.find(x=>x.id===selectedStrategy)||data.strategies[0],providerName=provider==='ubereats'?'Uber Eats':provider==='doordash'?'DoorDash':'',providerUrl=provider==='ubereats'?'https://www.ubereats.com/':'https://www.doordash.com/';
 app.innerHTML=`<div class="eyebrow">ORDER THE PAIRING</div><h1>${esc(data.meal)}, ready to find.</h1><p>Keep the dinner idea connected to <strong>${esc(data.show)}</strong>, then bring the real delivery estimate back to the TV.</p><div class="facts"><span class="pill">${data.people} people</span><span class="pill">${esc(data.diet)}</span><span class="pill">Budget guide ${esc(data.budget)}</span></div><div class="step">01 · CHOOSE THE SEARCH</div><div class="choice-grid">${data.strategies.map(x=>`<button class="choice ${x.id===chosen.id?'selected':''}" data-strategy="${x.id}"><strong>${esc(x.label)}</strong><span>${esc(x.query)}</span><small>${esc(x.detail)}</small></button>`).join('')}</div><div class="brief"><small>SEARCH PHRASE</small><strong>${esc(chosen.query)}</strong><button id="copy">Copy phrase</button></div><div class="step">02 · CHOOSE A PROVIDER</div><div class="provider-grid"><button class="${provider==='doordash'?'selected':''}" data-provider="doordash">DoorDash</button><button class="${provider==='ubereats'?'selected':''}" data-provider="ubereats">Uber Eats</button></div>${provider?`<a class="provider-link primary" id="open-provider" href="${providerUrl}" target="_blank" rel="noopener">Copy search & open ${providerName} ↗</a><p class="note">Search, choose a restaurant, review ingredients and fees, and place the order in ${providerName}. Crave Frame does not receive your login, cart, payment, or tracking.</p><div class="step">03 · BRING BACK THE REAL ETA</div><label class="eta">Minutes shown at checkout<input id="eta" type="number" inputmode="numeric" min="15" max="120" value="${etaMinutes}"></label><button class="primary confirm-order" id="confirm-order">I placed the order · sync my TV →</button>`:'<p class="note">Choose where you want to finish checkout.</p>'}<p class="note">For allergies, verify menu ingredients and restaurant handling directly with the provider and restaurant.</p>`;
 app.querySelectorAll('[data-strategy]').forEach(x=>x.onclick=()=>{selectedStrategy=x.dataset.strategy;order();});app.querySelectorAll('[data-provider]').forEach(x=>x.onclick=()=>{provider=x.dataset.provider;order();});
 document.querySelector('#copy').onclick=()=>run(async()=>{if(!navigator.clipboard)throw Error('Press and hold the phrase to copy it.');await navigator.clipboard.writeText(chosen.query);document.querySelector('#copy').textContent='Copied ✓';});
 document.querySelector('#open-provider')?.addEventListener('click',()=>{navigator.clipboard?.writeText(chosen.query).catch(()=>{});});
 document.querySelector('#eta')?.addEventListener('input',e=>etaMinutes=Number(e.target.value));
 document.querySelector('#confirm-order')?.addEventListener('click',()=>run(async()=>{etaMinutes=Number(document.querySelector('#eta').value);if(!Number.isInteger(etaMinutes)||etaMinutes<15||etaMinutes>120)throw Error('Enter the provider estimate from 15 to 120 minutes.');data=await api('confirm',{provider,strategy:chosen.id,etaMinutes});order();}));
}
async function load(){data=await api();if(data.kind==='pantry'){items=data.items.join('\n');pantry();}else if(data.kind==='order'){selectedStrategy=data.selectedStrategy||'';provider=data.preferredProvider||'';order();}else{enough=new Set(data.enough);try{checked=new Set(JSON.parse(localStorage.getItem(storageKey())||'[]'));}catch{checked=new Set();}editing=false;shopping();}app.setAttribute('aria-busy','false');}
run(load);

let polling=false;
setInterval(async()=>{if(busy||polling||data?.kind!=='shopping')return;polling=true;try{const fresh=await api();if(fresh.signature!==data.signature){data=fresh;enough=new Set();checked=new Set();editing=true;shopping();status.textContent='Your recipe or guest count changed. Review quantities for the updated evening.';}else if(fresh.revision!==data.revision){if(editing){status.textContent='Someone updated this shopping list. Refresh the approved plan before saving your draft.';}else{data=fresh;enough=new Set(data.enough);shopping();status.textContent='Shopping quantities updated from another screen.';}}}catch{status.textContent='Could not refresh the approved plan. Check the connection before using these quantities.';}finally{polling=false;}},10000);
