// 20 deliberately specified fillings × 20 different cooking methods = 400 dishes.
// These are original demo recipes, not kitchen-tested recipes. Each ingredient
// marked cooked is required ready-cooked; total times assume that starting point.
/** @typedef {[string,number,string]} Ingredient */
/** @returns {Ingredient} */
const I=(n,a,u='g')=>[n,a,u];
/** @type {Array<[string,string,string,string,string]>} */
const profiles=[
 ['Smoky black bean & pepper','Canned black beans, drained','Cooked roasted bell pepper','Smoked paprika','Americas'],
 ['Lemon chickpea & zucchini','Canned chickpeas, drained','Cooked zucchini','Dried oregano','Mediterranean'],
 ['Thyme white bean & mushroom','Canned white beans, drained','Cooked mushrooms','Dried thyme','European'],
 ['Cumin lentil & carrot','Cooked green lentils','Cooked carrots','Ground cumin','Mediterranean'],
 ['Basil chickpea & broccoli','Canned chickpeas, drained','Cooked broccoli','Dried basil','Mediterranean'],
 ['Paprika pinto bean & corn','Canned pinto beans, drained','Canned sweetcorn, drained','Smoked paprika','Americas'],
 ['Butter bean & spinach','Canned butter beans, drained','Cooked spinach, squeezed dry','Ground nutmeg','European'],
 ['Sage chickpea & squash','Canned chickpeas, drained','Cooked butternut squash','Dried sage','European'],
 ['Dill lentil & beet','Cooked green lentils','Cooked beetroot','Dried dill','European'],
 ['Mint white bean & pea','Canned white beans, drained','Cooked peas','Dried mint','European'],
 ['Oregano chickpea & eggplant','Canned chickpeas, drained','Cooked eggplant','Dried oregano','Mediterranean'],
 ['Cumin black bean & sweet potato','Canned black beans, drained','Cooked sweet potato','Ground cumin','Americas'],
 ['Curry white bean & cauliflower','Canned white beans, drained','Cooked cauliflower','Mild curry powder','Asian'],
 ['Parsley lentil & green bean','Cooked green lentils','Cooked green beans','Dried parsley','Mediterranean'],
 ['Lemon white bean & artichoke','Canned white beans, drained','Jarred artichoke hearts, drained','Dried oregano','Mediterranean'],
 ['Basil butter bean & tomato','Canned butter beans, drained','Cooked roasted tomatoes','Dried basil','Mediterranean'],
 ['Caraway pinto bean & cabbage','Canned pinto beans, drained','Cooked cabbage','Ground caraway','European'],
 ['Thyme white bean & leek','Canned white beans, drained','Cooked leeks','Dried thyme','European'],
 ['Oregano chickpea & fennel','Canned chickpeas, drained','Cooked roasted fennel','Dried oregano','Mediterranean'],
 ['Chili kidney bean & pepper','Canned kidney beans, drained','Cooked roasted bell pepper','Mild chili powder','Americas']
];
const slug=s=>s.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const olive=(n=1)=>I('Olive oil',n,'tbsp');
const water=n=>I('Water',n,'ml');
const broth=n=>I('Vegetable broth',n,'ml');
const swap={from:'Plain yogurt',to:'Unsweetened plant-based yogurt',amount:60,unit:'g',reason:'Use unsweetened plant-based yogurt for the finishing sauce. The recipe specifies dairy-free bread, pastry or cheese wherever those are used; check package labels.'};
const finish=['Finish and serve','Stir lemon juice into {finish}. Season the dish to taste and serve with the lemon yogurt alongside or spooned over.',0];
const prep=(p)=>['Prepare the filling',`Drain ${p[1].toLowerCase()} well and rinse if canned. Finely chop ${p[2].toLowerCase()} and drain excess moisture. Both the pulses and vegetables must already be cooked. Measure ${p[3].toLowerCase()}; reserve lemon juice and yogurt for the finish.`,0];
const filling=p=>`${p[1].toLowerCase()}, ${p[2].toLowerCase()} and ${p[3].toLowerCase()}`;
const warm=(p)=>['Warm the filling',`Heat the olive oil in a skillet over medium heat. Add ${filling(p)} and cook, stirring, for 6–8 minutes until hot throughout. Add a splash of water if needed.`,360];
/** @typedef {{suffix:string,category:string,image:string,minutes:number,items:Ingredient[],steps:(p:string[])=>Array<[string,string,number]>,moods:string[]}} Method */
/** @type {Method[]} */
const methods=[
 {suffix:'burgers',category:'Burgers',image:'burgers',minutes:40,moods:['Adventure','Lighthearted'],items:[I('Rolled oats',60),I('Chickpea flour',30),I('Dairy-free burger buns',2,'pieces'),I('Lettuce',40),olive(2)],steps:p=>[prep(p),['Shape the patties',`Mash ${p[1].toLowerCase()} thoroughly. Mix with finely chopped ${p[2].toLowerCase()}, ${p[3].toLowerCase()}, oats and chickpea flour. Rest 10 minutes so oats absorb moisture. Form four thin patties; if crumbly add water a teaspoon at a time, or if too wet add a little more oats.`,600],['Cook','Heat olive oil in a nonstick skillet over medium heat. Cook patties 5–6 minutes per side until firm, browned and hot throughout. Turn gently; cook in batches if necessary.',600],['Assemble','Warm the buns. Add lettuce and two small patties per bun. Serve extra patties alongside if your buns are small.',0],finish]},
 {suffix:'stuffed baked potatoes',category:'Stuffed potatoes',image:'potatoes',minutes:35,moods:['Cozy','Adventure'],items:[I('Baking potatoes',500),olive()],steps:p=>[prep(p),['Cook the potatoes','Scrub potatoes and prick several times with a fork. Microwave on a microwave-safe plate for 10–14 minutes, turning halfway, until a knife slides easily through the center. Add time in 2-minute bursts if still firm. Rest 2 minutes.',600],warm(p),['Fill','Split the hot potatoes carefully and fluff the inside with a fork. Divide the hot filling between them.',0],finish]},
 {suffix:'quesadillas',category:'Quesadillas',image:'tacos',minutes:25,moods:['Adventure','Lighthearted'],items:[I('Dairy-free flour tortillas',4,'pieces'),I('Plant-based grated cheese',80),olive()],steps:p=>[prep(p),['Make the filling',`Mash half of ${p[1].toLowerCase()} and combine with ${p[2].toLowerCase()} and ${p[3].toLowerCase()}. Spread thinly over half of each tortilla, add plant-based cheese, then fold closed.`,0],['Toast','Brush a wide nonstick skillet with olive oil over medium-low heat. Cook folded tortillas 3–4 minutes per side, in batches, until crisp and the filling is hot. Follow cheese melting instructions; lower heat if tortillas brown too quickly.',420],['Slice','Rest for a minute, then cut into wedges. Keep completed quesadillas warm while cooking the rest.',0],finish]},
 {suffix:'risotto',category:'Risotto',image:'risotto',minutes:45,moods:['Cozy','Romantic'],items:[I('Arborio rice',150),I('Onion',80),broth(700),olive()],steps:p=>[prep(p),['Start the rice','Keep broth hot in a saucepan. Finely dice onion. Warm olive oil in another pan and soften onion for 5 minutes. Stir in dry arborio rice for 1 minute.',300],['Cook the risotto',`Add hot broth a ladle at a time, stirring regularly and letting each addition absorb. Cook 18–22 minutes until rice is tender with a slight bite. Stir in ${filling(p)} for the final 6 minutes. Add extra hot water if the rice needs more cooking.`,1080],['Rest','Remove from heat and rest 2 minutes. The risotto should flow gently, not stand in a stiff mound; loosen with a little hot water if needed.',0],finish]},
 {suffix:'gnocchi skillet',category:'Gnocchi',image:'pasta',minutes:25,moods:['Cozy','Romantic'],items:[I('Egg-free potato gnocchi',350),I('Tomato passata',150),olive()],steps:p=>[prep(p),['Cook the gnocchi','Cook gnocchi in simmering water following its packet instructions, then drain. Reserve a small cup of the cooking water.',0],['Make the sauce',`Heat olive oil over medium heat. Add ${filling(p)} and tomato passata. Simmer for 8 minutes until the filling is hot throughout. Loosen with a splash of gnocchi water.`,480],['Combine','Fold cooked gnocchi into the sauce and heat together for 1–2 minutes without crushing them.',0],finish]},
 {suffix:'polenta bowls',category:'Polenta',image:'bowl',minutes:25,moods:['Cozy','Romantic'],items:[I('Quick-cook polenta',100),broth(500),olive()],steps:p=>[prep(p),warm(p),['Cook the polenta','Bring broth to a simmer. Whisk in quick-cook polenta gradually. Stir over low heat for the time specified on its package, usually 3–5 minutes, until thick and smooth. Add hot water if needed.',0],['Plate','Divide hot polenta between two bowls. Spoon the warm filling over the top and serve promptly before the polenta sets.',0],finish]},
 {suffix:'stuffed peppers',category:'Stuffed peppers',image:'peppers',minutes:55,moods:['Adventure','Romantic'],items:[I('Large bell peppers',2,'pieces'),I('Cooked rice',150),I('Tomato passata',100),olive()],steps:p=>[prep(p),['Prepare peppers','Heat oven to 200°C / 400°F. Halve bell peppers lengthwise, removing seeds. Brush a baking dish with olive oil and place peppers cut-side up.',0],['Stuff',`Mix ${filling(p)} with cooked rice and tomato passata. Fill the pepper halves. Put any extra filling alongside them in the dish. Add 3 tablespoons water to the dish and cover with foil.`,0],['Bake','Bake covered for 25 minutes, then uncover and bake 10–15 minutes more until peppers are tender and filling is hot throughout.',1500],finish]},
 {suffix:'puff-pastry pot pies',category:'Savory pies',image:'bake',minutes:45,moods:['Cozy','Romantic'],items:[I('Dairy-free puff pastry',150),I('Cornstarch',10),broth(150),olive()],steps:p=>[prep(p),['Make the filling',`Heat oven to 200°C / 400°F. Heat olive oil in a skillet and add ${filling(p)}. Mix cornstarch with cold broth, pour it in and simmer for 3–4 minutes until thickened and hot.`,240],['Top the pies','Divide filling between two ovenproof dishes. Cut puff pastry to cover each dish. Lay over the filling, lightly press the edges, and cut a small steam vent in the center.',0],['Bake','Bake for 20–25 minutes, or according to the pastry packet, until the pastry is risen, golden and cooked through. Rest 5 minutes before serving.',1200],finish]},
 {suffix:'savory crumble',category:'Savory crumbles',image:'bake',minutes:45,moods:['Cozy','Adventure'],items:[I('Rolled oats',50),I('Plain flour',40),I('Olive oil',3,'tbsp'),I('Tomato passata',150)],steps:p=>[prep(p),['Make the topping','Heat oven to 200°C / 400°F. Mix oats and flour with 2 tablespoons olive oil and 1 tablespoon water to form loose crumbs.',0],['Fill the dish',`Grease a small baking dish with the remaining olive oil. Combine ${filling(p)} with passata and spread into the dish. Sprinkle the crumble evenly on top.`,0],['Bake','Bake for 25–30 minutes until the topping is golden and the filling is bubbling hot. Rest for 5 minutes before serving.',1500],finish]},
 {suffix:'chickpea pancakes',category:'Savory pancakes',image:'fritters',minutes:40,moods:['Lighthearted','Adventure'],items:[I('Chickpea flour',120),water(200),olive(2)],steps:p=>[prep(p),['Mix batter',`Whisk chickpea flour with the water and ${p[3].toLowerCase()} until smooth. Mash the pulses and finely chop the vegetables; fold both into the batter. Rest for 5 minutes. Add water a tablespoon at a time if too thick to spoon.`,0],['Pan-cook','Heat a little olive oil in a nonstick pan over medium-low heat. Spoon small pancakes into the pan, flatten to about 1 cm thick and cook 4–5 minutes per side, until set through the center and golden. Use remaining oil for subsequent batches.',480],['Keep warm','Transfer cooked pancakes to a warm plate. Cut one open to check the chickpea batter is fully set; cook longer over low heat if needed.',0],finish]},
 {suffix:'fritters',category:'Fritters',image:'fritters',minutes:35,moods:['Adventure','Lighthearted'],items:[I('Chickpea flour',80),water(60),olive(2)],steps:p=>[prep(p),['Mix',`Mash ${p[1].toLowerCase()}. Mix with finely chopped ${p[2].toLowerCase()}, ${p[3].toLowerCase()}, chickpea flour and water. The mixture should hold together on a spoon. Add a little flour if very wet.`,0],['Fry','Heat olive oil over medium-low heat in a nonstick pan. Make eight small, flattened fritters. Cook in batches for 4–5 minutes per side, until golden, firm and hot throughout. Keep them thin so the flour cooks through.',480],['Rest','Rest on a warm plate for 2 minutes. Check one fritter is set inside; return to low heat if its center is still wet.',0],finish]},
 {suffix:'couscous parcels',category:'Couscous parcels',image:'bowl',minutes:35,moods:['Adventure','Romantic'],items:[I('Dry couscous',120),broth(150),olive()],steps:p=>[prep(p),['Prepare couscous','Heat oven to 200°C / 400°F. Pour boiling broth over couscous, cover and stand for the time on its package, usually 5 minutes. Fluff with a fork.',0],['Make parcels',`Mix couscous with olive oil and ${filling(p)}. Divide between two large sheets of baking parchment, add a tablespoon water to each, and fold the edges firmly to seal. Place on a tray.`,0],['Bake','Bake for 15–20 minutes until the filling is hot throughout. Open parcels carefully away from your face to release steam.',900],finish]},
 {suffix:'pita pockets',category:'Pita pockets',image:'tacos',minutes:20,moods:['Lighthearted','Adventure'],items:[I('Dairy-free pita breads',2,'pieces'),I('Cucumber',100),I('Lettuce',40),olive()],steps:p=>[prep(p),warm(p),['Prepare the bread','Warm pita breads following their packet instructions. Slice cucumber and shred lettuce. Cut an opening in each pita.',0],['Fill','Divide the hot filling between pita pockets and add cucumber and lettuce. Put any filling that does not fit alongside the pitas.',0],finish]},
 {suffix:'toasted sandwiches',category:'Toasted sandwiches',image:'toast',minutes:25,moods:['Cozy','Lighthearted'],items:[I('Dairy-free sandwich bread',4,'slices'),I('Plant-based grated cheese',60),olive()],steps:p=>[prep(p),['Mix the filling',`Mash ${p[1].toLowerCase()} and combine with finely chopped ${p[2].toLowerCase()} and ${p[3].toLowerCase()}. Divide between two slices of bread, sprinkle with plant-based cheese, and close with the other slices.`,0],['Toast','Brush the outside with olive oil. Cook in a skillet over medium-low heat for 4–5 minutes per side, pressing gently, until golden and hot throughout. Cover the pan briefly if the filling needs more heating.',480],['Slice','Rest 1 minute, then slice the sandwiches in half. Serve the yogurt as a dip alongside.',0],finish]},
 {suffix:'orzo pot',category:'Orzo pots',image:'pasta',minutes:35,moods:['Cozy','Romantic'],items:[I('Dry orzo',150),broth(500),I('Onion',80),I('Tomato paste',1,'tbsp'),olive()],steps:p=>[prep(p),['Start the base','Dice onion. Heat olive oil in a deep pan and soften onion for 5 minutes. Stir in tomato paste and dry orzo.',300],['Simmer',`Add broth and ${filling(p)}. Simmer gently for the orzo package cooking time, usually 10–12 minutes, stirring frequently to prevent sticking. Add hot water if it becomes dry before the orzo is tender.`,600],['Check and rest','Check that orzo is tender and the whole dish is hot throughout. Rest off the heat for 2 minutes before serving.',0],finish]},
 {suffix:'fried rice',category:'Fried rice',image:'bowl',minutes:25,moods:['Adventure','Lighthearted'],items:[I('Cooked rice',250),I('Soy sauce',1,'tbsp'),I('Scallions',30),olive()],steps:p=>[prep(p),['Prepare the rice','Use cooked rice that has been stored chilled according to its packaging. Break up clumps with a fork and slice scallions.',0],['Stir-fry',`Heat olive oil over medium-high heat. Stir-fry ${filling(p)} for 3–4 minutes. Add rice and soy sauce and cook, stirring, for 5–6 minutes until the rice and filling are steaming hot throughout.`,480],['Finish the rice','Fold in scallions and divide between bowls. Serve promptly and avoid reheating the rice again.',0],finish]},
 {suffix:'stuffed mushrooms',category:'Stuffed mushrooms',image:'bowl',minutes:40,moods:['Cozy','Romantic'],items:[I('Large flat mushrooms',4,'pieces'),I('Dairy-free breadcrumbs',40),olive(2)],steps:p=>[prep(p),['Prepare caps','Heat oven to 200°C / 400°F. Wipe mushroom caps clean and remove stalks; chop the stalks finely. Brush the caps with half the olive oil and arrange on a baking tray.',0],['Fill',`Mash the pulses and mix with the chopped cooked vegetables, mushroom stalks, ${p[3].toLowerCase()} and breadcrumbs. Divide among mushroom caps and drizzle with the remaining olive oil.`,0],['Bake','Bake 20–25 minutes until the mushrooms are tender and the filling is hot throughout. If topping browns too quickly, cover loosely with foil.',1200],finish]},
 {suffix:'potato cakes',category:'Potato cakes',image:'fritters',minutes:35,moods:['Cozy','Adventure'],items:[I('Cooked potatoes',300),I('Cornstarch',25),olive(2)],steps:p=>[prep(p),['Shape',`Mash cooked potatoes and pulses. Add finely chopped cooked vegetables, ${p[3].toLowerCase()} and cornstarch. Shape into six patties about 1 cm thick. If very soft, rest for 5 minutes and handle gently.`,0],['Cook','Heat olive oil in a nonstick pan over medium heat. Cook patties in batches for 5 minutes per side until a firm golden crust forms and they are hot throughout. Let a crust form before turning.',600],['Rest','Rest potato cakes for 2 minutes to firm up, then divide between plates.',0],finish]},
 {suffix:'savory muffins',category:'Savory muffins',image:'bake',minutes:50,moods:['Lighthearted','Adventure'],items:[I('Chickpea flour',150),I('Baking powder',1,'tsp'),water(180),olive(2)],steps:p=>[prep(p),['Make batter',`Heat oven to 190°C / 375°F. Grease six large muffin cups with a little olive oil. Whisk chickpea flour, baking powder, ${p[3].toLowerCase()}, water and remaining oil. Mash pulses, finely chop vegetables and fold both into the batter.`,0],['Bake','Divide batter among the muffin cups. Bake 25–30 minutes until the tops are golden, centers feel firm and a skewer inserted in the center comes out without wet batter. Add time if needed.',1500],['Cool','Cool in the tin for 10 minutes before loosening and removing the muffins. Serve three per person as a light supper.',600],finish]},
 {suffix:'lettuce cups',category:'Lettuce cups',image:'salad',minutes:20,moods:['Lighthearted','Adventure'],items:[I('Large lettuce leaves',8,'pieces'),I('Cucumber',100),I('Cooked quinoa',150),olive()],steps:p=>[prep(p),warm(p),['Prepare cups','Wash and dry lettuce leaves. Dice cucumber. Heat cooked quinoa according to its package directions until hot throughout, then let it cool slightly so it does not wilt the lettuce.',0],['Assemble','Divide quinoa, warm filling and cucumber among lettuce leaves. Use two leaves per cup if needed. Serve remaining filling in a small bowl alongside.',0],finish]}
];
export const expandedRecipes=methods.flatMap(method=>profiles.map(p=>{
 const name=p[0]+' '+method.suffix;
 return {id:'expanded-'+slug(name),name,category:method.category,image:method.image,cuisine:p[4],minutes:method.minutes,effort:method.minutes<=30?'Easy':'Relaxed',moods:method.moods,subtitle:'A '+method.suffix+' supper using ready-cooked vegetables and pulses.',ingredients:[I(p[1],200),I(p[2],150),I(p[3],p[3]==='Ground nutmeg'?0.25:1,'tsp'),I('Lemon juice',1,'tbsp'),...method.items,I('Plain yogurt',60)],swap,steps:method.steps(p),photoNote:'Representative category photograph',methodFamily:method.category};
}));
