import {titleKey,canonicalShow,distinctShows} from './identity.js';
import {storyRecipes} from './story-recipes.js';
import {proteinRecipes} from './protein-recipes.js';
import {extraMeals} from './extra-meals.js';
import {recipeLibrary} from './recipe-library.js';
import {expandedRecipes} from './expanded-recipes.js';
import {everydayRecipes} from './everyday-recipes.js';
export const moods = ['Cozy','Lighthearted','Adventure','Romantic'];
export const meals = [
 ...storyRecipes,
 {id:'mushroom-toast',name:'Mushroom toast & crispy potatoes',subtitle:'Golden edges. Earthy mushrooms. A little comfort.',image:'toast',minutes:30,effort:'Easy',moods:['Cozy','Adventure'],ingredients:[['Mushrooms',250,'g'],['Sourdough',2,'slices'],['Potatoes',300,'g'],['Garlic',2,'cloves'],['Thyme',1,'tsp'],['Butter',25,'g'],['Olive oil',1,'tbsp']],swap:{from:'Butter',to:'Olive oil',amount:2,unit:'tbsp',reason:'Olive oil keeps the mushrooms rich and makes this recipe plant-based. Use medium heat and let them brown before stirring.'},steps:[['Start the potatoes','Heat the oven to 220°C / 425°F. Cut the potatoes into small, even pieces. Toss with the listed olive oil and a pinch of salt. Roast on a tray until golden and tender, about 25 minutes.',1500],['Prepare the mushrooms','Wipe and slice the mushrooms. Mince the garlic and pick the thyme leaves.',0],['Build the flavor','Heat {fat} in a wide pan over medium heat. Add mushrooms in one layer. Cook until browned, about 8 minutes. Stir in garlic and thyme for the final minute.',480],['Toast the bread','Toast the sourdough until crisp and golden, about 3 minutes. Check that the potatoes are tender; give them longer if needed.',180],['Bring it together','Spoon mushrooms onto the toast. Serve with crispy potatoes. Season to taste and settle in.',0]]},
 {id:'garlic-toast',name:'Garlic mushrooms on toast',subtitle:'A warm skillet supper, without the extra prep.',image:'toast',minutes:15,effort:'Easy',moods:['Cozy','Romantic'],ingredients:[['Mushrooms',250,'g'],['Sourdough',2,'slices'],['Garlic',2,'cloves'],['Thyme',1,'tsp'],['Butter',25,'g']],swap:{from:'Butter',to:'Olive oil',amount:2,unit:'tbsp',reason:'Use olive oil in place of butter for a plant-based skillet supper.'},steps:[['Prepare','Slice mushrooms and mince garlic. Pick the thyme leaves.',0],['Sauté','Heat {fat} over medium heat. Cook mushrooms until browned and tender, about 8 minutes. Add garlic and thyme for the final minute.',480],['Toast','Toast sourdough until crisp, about 3 minutes.',180],['Serve','Spoon the mushrooms over toast and season to taste. Dinner is ready.',0]]},
 {id:'tomato-pasta',name:'Tomato & basil pasta',subtitle:'Bright tomatoes, fresh basil, a generous twirl.',image:'pasta',minutes:25,effort:'Easy',moods:['Lighthearted','Romantic'],ingredients:[['Pasta',180,'g'],['Cherry tomatoes',300,'g'],['Garlic',2,'cloves'],['Basil',10,'leaves'],['Olive oil',2,'tbsp'],['Parmesan',30,'g']],swap:{from:'Parmesan',to:'Toasted breadcrumbs',amount:3,unit:'tbsp',reason:'Toasted breadcrumbs add a savory crunch without dairy. Choose egg-free pasta for a plant-based meal.'},steps:[['Get ready','Bring a large pot of salted water to a boil. Halve the tomatoes and slice garlic.',0],['Make the sauce','Warm olive oil over medium-low heat. Cook garlic briefly, then add tomatoes. Simmer until juicy, about 10 minutes.',600],['Cook the pasta','Cook pasta according to its packet instructions. Reserve a mug of pasta water before draining.',0],['Toss and finish','Toss pasta with the tomatoes and a splash of pasta water. Tear in basil. Top with {finish} and serve.',0]]},
 {id:'roasted-pasta',name:'Slow-roasted tomato pasta',subtitle:'Jammy tomatoes and a comforting bowl to share.',image:'pasta',minutes:40,effort:'Relaxed',moods:['Cozy','Romantic'],ingredients:[['Pasta',180,'g'],['Cherry tomatoes',350,'g'],['Garlic',3,'cloves'],['Basil',10,'leaves'],['Olive oil',2,'tbsp'],['Parmesan',30,'g']],swap:{from:'Parmesan',to:'Toasted breadcrumbs',amount:3,unit:'tbsp',reason:'A crunchy breadcrumb finish replaces cheese. Choose egg-free pasta if eating plant-based.'},steps:[['Roast the tomatoes','Heat oven to 200°C / 400°F. Put halved tomatoes and peeled garlic in a baking dish with olive oil. Roast until softened, about 30 minutes.',1800],['Cook pasta','Near the end of roasting, cook pasta according to packet instructions. Save a mug of the cooking water.',0],['Make it saucy','Mash the softened garlic into the tomatoes. Toss with the drained pasta, basil, and enough pasta water to coat.',0],['Finish','Top with {finish}. Serve in warm bowls.',0]]},
 {id:'margherita',name:'Margherita pizza',subtitle:'Crisp crust, bubbling cheese, fresh basil.',image:'pizza',familiar:true,minutes:30,effort:'Relaxed',moods:['Adventure','Lighthearted'],ingredients:[['Pizza dough',400,'g'],['Tomato sauce',120,'g'],['Mozzarella',125,'g'],['Basil',8,'leaves'],['Olive oil',1,'tbsp']],swap:{from:'Mozzarella',to:'Plant-based mozzarella',amount:125,unit:'g',reason:'A plant-based mozzarella keeps the shared pizza format. Follow its package instructions for melting.'},steps:[['Heat the oven','Heat oven to 240°C / 465°F with a baking tray inside. Follow your dough package instructions if they differ.',0],['Shape','Divide dough into two personal pizzas. Stretch on baking paper to fit the tray.',0],['Top','Spread tomato sauce thinly and add {finish}. Drizzle with olive oil.',0],['Bake','Transfer carefully onto the hot tray. Bake until the crust is cooked through and golden, about 12–15 minutes. Check early; ovens vary.',720],['Share','Add basil, let cool briefly, then slice and share.',0]]},
 {id:'flatbread',name:'Basil & tomato flatbreads',subtitle:'Pizza-night energy. Weeknight effort.',image:'pizza',minutes:15,effort:'Easy',moods:['Adventure','Lighthearted'],ingredients:[['Flatbreads',2,'pieces'],['Tomato sauce',100,'g'],['Mozzarella',100,'g'],['Basil',8,'leaves'],['Olive oil',1,'tbsp']],swap:{from:'Mozzarella',to:'Plant-based mozzarella',amount:100,unit:'g',reason:'Choose plant-based mozzarella and dairy-free flatbreads to suit a plant-based preference.'},steps:[['Heat','Heat oven to 220°C / 425°F. Place flatbreads on a baking tray.',0],['Top','Spread with tomato sauce, add {finish}, and drizzle with olive oil.',0],['Bake','Bake until hot throughout and crisp at the edges, about 8 minutes; follow flatbread packet instructions if different.',480],['Finish','Scatter basil over the top and cut into wedges.',0]]}
];
export const shows = [
 {id:'last-guest',name:'The Last Guest',kind:'Movie',minutes:102,mood:'Cozy',genre:'Cozy mystery',scene:'manor',family:true,description:'A storm, a country house, and one guest with a story that does not quite add up.',tags:['Gentle suspense','Rainy evenings'],pairing:'Earthy, comforting flavors echo its candlelit country-house atmosphere.'},
 {id:'bookshop',name:'The Bookshop Case',kind:'TV episode',minutes:42,mood:'Cozy',genre:'Gentle mystery',scene:'manor',family:true,description:'A bookseller finds a handwritten clue tucked inside a returned novel. One complete case, one cozy evening.',tags:['One complete case','Quiet wit'],pairing:'A warm, unfussy supper fits this small-town mystery.'},
 {id:'next-door',name:'Next Door',kind:'TV episode',minutes:28,mood:'Cozy',genre:'Comfort comedy',scene:'manor',family:true,description:'An unlikely friendship begins over a borrowed saucepan and a very stubborn front door.',tags:['Comfort watch','Warm humor'],pairing:'Its everyday warmth suits a comforting dinner with little preparation.'},
 {id:'table-two',name:'A Table for Two',kind:'Movie',minutes:88,mood:'Romantic',genre:'Romantic comedy',scene:'coast',family:false,description:'Two strangers. One missed train. An unexpected evening in a seaside town.',tags:['Warm humor','Seaside escape'],pairing:'The seaside setting and easygoing romance complement a bright, leisurely dinner.'},
 {id:'postcards',name:'Postcards at Sunset',kind:'TV episode',minutes:35,mood:'Romantic',genre:'Romantic drama',scene:'coast',family:false,description:'A travel writer follows an unsigned postcard to a quiet café by the sea.',tags:['Gentle romance','Golden-hour mood'],pairing:'A fresh, aromatic meal carries the relaxed atmosphere beyond the screen.'},
 {id:'sunday',name:'Sunday on the Coast',kind:'Movie',minutes:96,mood:'Romantic',genre:'Romantic drama',scene:'coast',family:false,description:'Two old friends reunite for a Sunday lunch that stretches into an unexpected adventure.',tags:['Slow afternoon','Second chances'],pairing:'An unhurried shared supper matches its slow coastal rhythm.'},
 {id:'weekend',name:'An Unexpected Weekend',kind:'Movie',minutes:94,mood:'Lighthearted',genre:'Comedy mystery',scene:'coast',family:true,description:'A lost suitcase sends three friends on a delightfully tangled weekend detour.',tags:['Playful mystery','Feel-good'],pairing:'Bright flavors suit its playful energy and easygoing humor.'},
 {id:'little-cafe',name:'The Little Café',kind:'TV episode',minutes:24,mood:'Lighthearted',genre:'Sitcom',scene:'coast',family:true,description:'Opening day at a tiny café brings big personalities and an improvised menu.',tags:['Quick laugh','Ensemble comedy'],pairing:'A simple, colorful meal keeps this short comedy night light.'},
 {id:'good-company',name:'Good Company',kind:'TV episode',minutes:32,mood:'Lighthearted',genre:'Feel-good comedy',scene:'coast',family:true,description:'A neighborhood supper club attempts its first potluck with charmingly mixed results.',tags:['Found family','Easygoing'],pairing:'A shareable meal complements its friendly supper-club setting.'},
 {id:'lantern',name:'The Lantern Trail',kind:'Movie',minutes:95,mood:'Adventure',genre:'Family adventure',scene:'lake',family:true,description:'Two siblings follow a trail of lanterns toward a forgotten lakeside observatory.',tags:['Family night','Outdoor wonder'],pairing:'A hearty, shareable dinner matches the spirit of an outdoor adventure.'},
 {id:'campfire',name:'Campfire Club',kind:'TV episode',minutes:38,mood:'Adventure',genre:'Family adventure',scene:'lake',family:true,description:'A group of friends turns an ordinary camping trip into a lakeside treasure hunt.',tags:['Together time','Light adventure'],pairing:'Casual food to share fits the campfire mood.'},
 {id:'wild-hour',name:'The Wild Hour',kind:'TV episode',minutes:44,mood:'Adventure',genre:'Nature documentary',scene:'lake',family:true,description:'An imagined journey through forest trails and quiet lakes, exploring the changing light of one day.',tags:['Nature escape','Calm discovery'],pairing:'A rustic dinner pairs with the forest-and-lake atmosphere.'}
];
shows.push(
 {id:'grand-budapest',name:'The Grand Budapest Hotel',kind:'Movie',minutes:99,mood:'Cozy',genre:'Comedy drama',scene:'manor',family:false,description:'A concierge and his young protégé become caught in an elaborate caper. A stylish choice for a darkly comic evening.',tags:['Wry humor','Hotel caper'],pairing:'A comforting mushroom supper complements the wintry hotel atmosphere.',source:'https://tv.apple.com/us/movie/the-grand-budapest-hotel/umc.cmc.1yrchfyt6pyg3g827zdo6br38',rating:'R'},
 {id:'detectorists',name:'Detectorists — S1 E1',kind:'TV episode',minutes:29,mood:'Cozy',genre:'Gentle comedy',scene:'lake',family:false,description:'Two metal-detecting friends pursue buried treasure in the English countryside. An understated, gently funny start to the series.',tags:['Quiet humor','Countryside'],pairing:'Earthy mushrooms and a relaxed supper fit its unhurried countryside mood.',source:'https://tv.apple.com/us/show/detectorists/umc.cmc.38iqc9rcb5f78oliz7tv5gx5j',rating:'TV-14'},
 {id:'only-murders',name:'Only Murders — True Crime',kind:'TV episode',minutes:33,mood:'Cozy',genre:'Comedy mystery · S1 E1',scene:'manor',family:false,description:'The first episode of Only Murders in the Building brings three neighbors together around an unexpected mystery.',tags:['Mystery night','Series premiere'],pairing:'A warm skillet dinner pairs with a conversational mystery night.',source:'https://tv.apple.com/us/show/only-murders-in-the-building/umc.cmc.7kd9yvyu5ecz1snkt4a35o12g',rating:'TV-MA'},
 {id:'chef',name:'Chef',kind:'Movie',minutes:114,mood:'Lighthearted',genre:'Food comedy drama',scene:'coast',family:false,description:'A chef finds a fresh start through a food-truck road trip with his son. Food and reconnection drive this warm comedy.',tags:['Food lovers','Road trip'],pairing:'A colorful, hands-on dinner carries its enthusiasm for cooking into your kitchen.',source:'https://tv.apple.com/us/movie/chef/umc.cmc.sbnir5fu1zxi3agh2u6yi1zn',rating:'R'},
 {id:'ratatouille',name:'Ratatouille',kind:'Movie',minutes:111,mood:'Adventure',genre:'Animated food adventure',scene:'coast',family:true,description:'An aspiring rat chef chases a culinary dream in Paris. A playful family choice for a night built around cooking.',tags:['Family night','Kitchen creativity'],pairing:'Making a shared pizza or tomato-based dinner brings its playful cooking spirit to the table.',source:'https://www.disneyplus.com/browse/entity-ab7c4e29-04f1-46dd-931a-d43be1ce0f8c',rating:'G'},
 {id:'paddington',name:'Paddington',kind:'Movie',minutes:96,mood:'Lighthearted',genre:'Family adventure',scene:'manor',family:true,description:'A young bear arrives in London and finds a new home with the Brown family. Warmth and gentle chaos set the tone.',tags:['Family night','Warmhearted'],pairing:'Easy food to share complements its welcoming, family-centered atmosphere.',source:'https://tv.apple.com/gb/movie/paddington/umc.cmc.759zk34s47omthqjyvc9i6pgo',rating:'PG'},
 {id:'before-sunrise',name:'Before Sunrise',kind:'Movie',minutes:101,mood:'Romantic',genre:'Romantic drama',scene:'coast',family:false,description:'Two travelers spend an evening walking and talking in Vienna. An intimate, conversation-led choice for date night.',tags:['Date night','Slow conversation'],pairing:'A leisurely pasta supper leaves room for the kind of conversation at the heart of the film.',source:'https://tv.apple.com/us/movie/before-sunrise/umc.cmc.65m3n3lrca1e6nljfyvhn76u0',rating:'R'}
);
export const mealById=id=>meals.find(x=>x.id===id);
export const showById=id=>shows.find(x=>titleKey(x)===titleKey(id));
export const defaults={people:2,cookLevel:'Regular',mood:'Cozy',watchTime:120,cookTime:30,effort:'Any',diet:'No preference',family:false,format:'Any',catalog:'Real titles',pairingStyle:'Atmosphere'};

shows.push({id:'avengers',name:'The Avengers',kind:'Movie',minutes:143,mood:'Adventure',genre:'Superhero action',scene:'lake',family:false,description:'Earth’s heroes assemble to defend New York. A full-length action night after a relaxed sharing supper.',tags:['Teamwork','Action'],pairing:'Sharing tacos fit the ensemble spirit.',source:'https://www.themoviedb.org/movie/24428',rating:'Not verified',releaseYear:'2012',posterPath:'/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',provider:{type:'movie',id:24428}});
export function registerShows(items=[]){for(const original of items){if(!original)continue;const item=canonicalShow(original);const index=shows.findIndex(s=>titleKey(s)===item.id);if(index<0)shows.push(item);else if(item.provider)shows[index]=item;}}
const cuisines={'mushroom-toast':'European','garlic-toast':'European','tomato-pasta':'Mediterranean','roasted-pasta':'Mediterranean',margherita:'Mediterranean',flatbread:'Mediterranean'};
for(const meal of meals)meal.cuisine=cuisines[meal.id];
for(const show of shows)show.cuisine=['grand-budapest','detectorists','paddington','before-sunrise'].includes(show.id)?'European':show.id==='chef'?'Americas':show.id==='ratatouille'?'Mediterranean':'Any';

meals.push(...extraMeals);
for(const m of meals)m.category=m.image==='pasta'?'Pasta':m.image==='pizza'?'Flatbreads':'Toast & sandwiches';
meals.push(...recipeLibrary);
meals.push(...everydayRecipes,...expandedRecipes,...proteinRecipes);
export const mealCategories=['All recipes',...new Set(meals.map(m=>m.category))];
export const mealCuisines=['Any cuisine',...new Set(meals.map(m=>m.cuisine))];
export function filterMeals(query='',category='All recipes',maxMinutes=60,cuisine='Any cuisine'){const q=query.trim().toLowerCase();return meals.filter(m=>(category==='All recipes'||m.category===category)&&(cuisine==='Any cuisine'||m.cuisine===cuisine)&&m.minutes<=maxMinutes&&[m.name,m.subtitle,m.cuisine,m.category,...m.ingredients.map(i=>i[0])].join(' ').toLowerCase().includes(q));}

for(const m of meals){m.catalogTier=expandedRecipes.includes(m)?'variation':'core';m.recipeNote=m.catalogTier==='variation'?'Recipe variation. Uses ready-cooked fillings where listed; preparation from raw adds time. Original demo recipe, not kitchen-tested.':'Original demo recipe. Times are estimates; allow extra time for preparation. Dish photography is illustrative.';}

// A balanced editorial shelf; the complete library remains searchable.
const shelf=[];
for(const m of [...everydayRecipes,...proteinRecipes,...storyRecipes,...meals.filter(m=>m.catalogTier==='core')]){if(shelf.includes(m))continue;const family=m.foodType||m.category||m.image;if(shelf.filter(x=>(x.foodType||x.category||x.image)===family).length>=8)continue;shelf.push(m);if(shelf.length===48)break;}
for(const m of meals.filter(m=>m.catalogTier==='core')){if(shelf.length>=48)break;if(!shelf.includes(m))shelf.push(m);}
for(const m of meals)m.featuredRecipe=shelf.includes(m);

const chickenPhoto=meals.find(m=>m.id==='chicken-pepper-tacos');if(chickenPhoto)chickenPhoto.image='chicken-pepper-tacos';

for(const id of ['tuna-rice-bowls','white-bean-toast']){const m=meals.find(m=>m.id===id);if(m)m.image=id;}

shows.splice(0,shows.length,...distinctShows(shows));

// Editorial everyday choices: complete existing recipes with familiar meal formats.
for(const id of ["tomato-pasta","roasted-pasta","flatbread","pepper-pasta","chicken-pepper-tacos","chicken-basil-pasta","beef-rice-bowls","turkey-pita-pockets","salmon-lemon-pasta","tuna-rice-bowls","shrimp-pepper-tacos","recipe-smoky-black-bean-tacos","recipe-corn-and-pinto-bean-tacos","recipe-sweetcorn-and-potato-chowder","recipe-garden-minestrone","recipe-broccoli-and-garlic-pasta","recipe-mediterranean-pasta-salad","recipe-three-bean-chili"]){const meal=meals.find(m=>m.id===id);if(meal)meal.familiar=true;}
