// Recipes use ready-cooked proteins; follow their package storage and reheating directions.
const recipes=[
 ['chicken-pepper-tacos','Chicken & pepper tacos','Meat & poultry','Tacos & wraps','tacos','Americas',20,'Ready-cooked chicken strips',250,'Sliced bell peppers',150,'Tortillas',6,'pieces'],
 ['chicken-basil-pasta','Chicken & basil pasta','Meat & poultry','Pasta','pasta','Mediterranean',25,'Ready-cooked chicken strips',250,'Cherry tomatoes, halved',200,'Dry pasta',180,'g'],
 ['beef-rice-bowls','Beef & broccoli rice bowls','Meat & poultry','Rice bowls','bowl','Asian',20,'Ready-cooked beef strips',250,'Small broccoli florets',200,'Ready-cooked rice',300,'g'],
 ['turkey-pita-pockets','Turkey & pepper pita pockets','Meat & poultry','Tacos & wraps','tacos','Mediterranean',20,'Ready-cooked turkey strips',250,'Sliced bell peppers',150,'Pita breads',2,'pieces'],
 ['salmon-lemon-pasta','Salmon & lemon pasta','Fish & seafood','Pasta','pasta','Mediterranean',25,'Ready-cooked boneless salmon',250,'Frozen peas',150,'Dry pasta',180,'g'],
 ['tuna-rice-bowls','Tuna & sweetcorn rice bowls','Fish & seafood','Rice bowls','bowl','Americas',15,'Canned tuna, drained',240,'Canned sweetcorn, drained',150,'Ready-cooked rice',300,'g'],
 ['shrimp-pepper-tacos','Shrimp & pepper tacos','Fish & seafood','Tacos & wraps','tacos','Americas',20,'Ready-cooked peeled shrimp',250,'Sliced bell peppers',150,'Tortillas',6,'pieces'],
 ['chicken-couscous-bowls','Chicken & zucchini couscous bowls','Meat & poultry','Grain bowls','bowl','Mediterranean',25,'Ready-cooked chicken strips',250,'Zucchini, diced small',200,'Dry couscous',150,'g']
];
export const proteinRecipes=recipes.map(([id,name,foodType,category,image,cuisine,minutes,protein,amount,veg,vegAmount,base,baseAmount,unit])=>({id,name,foodType,category,image,cuisine,minutes,effort:'Easy',moods:['Cozy','Adventure','Lighthearted','Romantic'],subtitle:'An everyday supper with ready-cooked '+(foodType==='Fish & seafood'?'seafood.':'meat or poultry.'),ingredients:[[protein,amount,'g'],[veg,vegAmount,'g'],[base,baseAmount,unit],['Olive oil',1,'tbsp'],['Lemon juice',1,'tbsp'],['Dried basil',1,'tsp'],['Plain yogurt',60,'g']],swap:{from:'Plain yogurt',to:'Unsweetened plant yogurt',amount:60,unit:'g',reason:'Use plant yogurt for the topping if preferred. This change does not remove the meat or seafood and does not make the meal vegetarian or plant-based.'},steps:[
 ['Get ready','Use refrigerated ready-cooked protein within its package storage guidance. Prepare the vegetables, drain canned ingredients, and check fish for bones. These steps do not cook raw meat or seafood.',0],
 ['Prepare the base',base==='Dry pasta'?'Boil pasta in water according to its package until tender. Reserve a little cooking water, then drain.':base==='Dry couscous'?'Place couscous in a heatproof bowl. Add boiling water in the amount directed on its package, cover for the stated time, then fluff with a fork.':base==='Ready-cooked rice'?'Heat the ready-cooked rice according to its package until steaming hot. Keep covered while you finish the topping.':'Warm the breads according to their package directions. Keep covered so they stay soft.',0],
 ['Cook the vegetables','Heat olive oil in a skillet over medium heat. Add the prepared vegetables and a splash of water. Cook, stirring, until tender and hot throughout, about 5–8 minutes. Add dried basil.',300],
 ['Warm the protein','Add the ready-cooked protein to the vegetables. Follow its package reheating directions, warming until hot throughout and adding a splash of water if dry. Break tuna or salmon gently into chunks. Do not use raw protein with these instructions.',0],
 ['Serve','Combine with the prepared base or fill the warm breads. Finish with lemon juice and {finish}. Divide between the planned number of people and serve immediately.',0]
 ]}));
